### ISSUE TITLE
elpa issue?

### ISSUE THREAD

**Issue by AroundPeking** [deepmodeling/abacus-develop#2816] opened 2023-08-10 08:09 UTC
### Describe the bug

I wonder what is wrong in the error reporting. I have tried to use various version ABACUS, but all showed this error. When I moved to another server, no error happened. 
![image](https://github.com/deepmodeling/abacus-develop/assets/108850865/1462169a-a156-401d-b7d7-841bc5faab58)

### To Reproduce

Here are my input and ouput files.
ABACUS version: `commit fe3e4b313db1858d62c2cd6b92102d887c8abe65` (2023.07.23)
[task.002.tar.gz](https://github.com/deepmodeling/abacus-develop/files/12309983/task.002.tar.gz)

**Comment by hongriTianqi** [comment] 2023-08-10 23:49
@AroundPeking thanks for your report. In order to exclude possible cause from omp code, could you please try to run the job again with OMP_NUM_THREADS=1？You just need to add this before mpirun in your job submission script. Please let us know the results.

**Comment by AroundPeking** [comment] 2023-08-11 01:54
The same error with OMP_NUM_THREADS=1.
![image](https://github.com/deepmodeling/abacus-develop/assets/108850865/0583ae10-5cba-4325-adbb-01f2d5c3dcfe)

**Comment by hongriTianqi** [comment] 2023-08-14 04:46
@caic99 Would you please look into this issue?

**Comment by caic99** [comment] 2023-08-14 07:44
> @caic99 Would you please look into this issue?

@hongriTianqi Sorry, I have no ideas on it.

**Comment by hongriTianqi** [comment] 2023-09-08 01:17
@AroundPeking Has this issue been solved? If not, what is suggested for improving the performance of ABACUS later? Thank you.

**Comment by QuantumMisaka** [comment] 2023-09-08 01:29
@AroundPeking 
1. What's your environment in building ABACUS?
2. Have you tried toolchain method?

**Comment by hongriTianqi** [comment] 2023-09-08 04:49
- [x] Verify the issue is not a duplicate.
- [x] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by AroundPeking** [comment] 2023-09-08 14:19
> @AroundPeking Has this issue been solved? If not, what is suggested for improving the performance of ABACUS later? Thank you.

@hongriTianqi I have not solved it yet. In fact, it seems related to my building environment since one of my working sever works normally with `intel20u4` but another sever works wrong now with `oneapi2022.3`, while other softwares are same.

And I found it strange that it works right when I just change the `STRU` from a larger system of 400+ atoms in [task.002.tar.gz](https://github.com/deepmodeling/abacus-develop/files/12309983/task.002.tar.gz) to a smaller one of 50+ atoms in [test.zip](https://github.com/deepmodeling/abacus-develop/files/12560649/test.zip).




> @AroundPeking
> 
> 1. What's your environment in building ABACUS?
> 2. Have you tried toolchain method?

@QuantumMisaka 

1. here my environment: loaded `gcc11.2`, `oneapi22.3`, `miniconda3`, `cmake3.26.3`
my building:
![image](https://github.com/deepmodeling/abacus-develop/assets/108850865/60085032-ed82-4586-9db4-9de443b2494c)
![image](https://github.com/deepmodeling/abacus-develop/assets/108850865/725dfc33-885f-4b12-afda-5b96eddec8a2)
I am not sure whether I answer you clearly. You can ask me for more detail files.

3. No, I have no idea with toolchain method.

**Comment by hongriTianqi** [comment] 2023-09-09 07:34
@AroundPeking Thanks. There is another issue related to size limit #2002 and #2044, that might be related to this problem.

**Comment by yizeyi18** [comment] 2024-01-31 08:41
At which stage did your task failed? I tested it on my machine and the test task survived for more than 2 scf cycles. The test abacus is compiled with gcc-13.2.0, elpa-2023.05.001, openblas-0.3.23, openmpi-4.1.1 and fftw-3.3.10.
It seems you uses elpa-2021.11.001 and intel compiler. May you give a try on a newer version of elpa with your remaining environment?

**Comment by WHUweiqingzhou** [comment] 2024-09-14 05:01
We try v3.7.5, and find this error disappears.

**Closed as completed by WHUweiqingzhou** 2024-09-14 05:01 UTC
Labels: Compile & CICD & Docs & Dependencies
