### ISSUE TITLE
ERROR: PRICELL: NCELL != NTRANS !

### ISSUE THREAD

**Issue by Weizhang88** [deepmodeling/abacus-develop#2649] opened 2023-06-16 12:57 UTC
### Describe the bug

using abacus v3.2.4 for cell-relax, after 53 steps of relaxation, ERROR: PRICELL: NCELL != NTRANS ! The the cell-relax progress stoped. 
![image](https://github.com/deepmodeling/abacus-develop/assets/28947944/f411964e-3c9d-4643-a883-978ec7817517)

**Comment by Satinelamp** [comment] 2023-06-16 13:13
@Weizhang88. Could you share the input file?

**Comment by Satinelamp** [comment] 2023-06-16 13:23
My guess is that you might use `symmetry =1 ` for a supercell. Maybe trying to turn off `symmetry` is an option.

**Comment by Weizhang88** [comment] 2023-06-16 15:23
> My guess is that you might use `symmetry =1 ` for a supercell. Maybe trying to turn off `symmetry` is an option.

symmetry was not given in the input file, the default value was used. And the `symmetry =1` in the INPUT file from OUT dir. I will try with `symmetry =0`. Thanks.

**Comment by Satinelamp** [comment] 2023-06-17 04:06
@Weizhang88， Any update about the results?

**Comment by maki49** [comment] 2023-06-19 01:16
@Weizhang88 Please provide your working directory for us to debug.

**Comment by hongriTianqi** [comment] 2023-08-03 05:33
@Weizhang88 Does this issue still exist? Please let us know if you still have problems. Thanks!

**Comment by hongriTianqi** [comment] 2023-09-09 07:24
- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by hongriTianqi** [comment] 2023-09-09 07:26
We have not get your response for long. If the issue exists, please reopen it again and with more details to help us repeat the error. Thanks! @Weizhang88

**Closed as completed by hongriTianqi** 2023-09-09 07:26 UTC
Labels: Bugs
