### ISSUE TITLE
Official orbital files for Hf looks bad

### ISSUE THREAD

**Issue by dyzheng** [deepmodeling/abacus-develop#1795] opened 2023-01-12 13:47 UTC
### Describe the bug

Numerical orbital files of TZDP-10au/DZP-all-rcuts would lead to consequence :
"
 GE1    -1.217547e+04  0.000000e+00   4.516e-02  2.806e+00  
 GE2    -1.217510e+04  3.667840e-01   2.209e-02  2.614e+00  
 GE3    -1.217527e+04  -1.641128e-01  4.798e-03  2.615e+00  
 GE4    -1.217527e+04  -3.921919e-03  6.002e-04  2.621e+00  
 GE5    -1.217527e+04  6.532555e-06   3.036e-04  2.613e+00  
 GE6    -1.217527e+04  5.466013e-06   1.949e-04  2.709e+00  
 GE7    -1.217527e+04  -3.444956e-05  3.006e-05  2.626e+00  
 GE8    -1.217527e+04  -5.509167e-07  5.677e-06  2.619e+00  
 GE9    -1.217527e+04  -1.398167e-06  1.104e-06  2.602e+00  
 GE10   -1.217527e+04  2.463277e-07   1.464e-07  2.643e+00
"
Numerical orbital files of TZDP-9au/TZDP-8au/TZDP-7au would lead to consequence : 
" 
 GE1    -2.070325e+04  0.000000e+00   1.057e+00  1.154e+01  
 GE2    -2.665975e+04  -5.956500e+03  7.395e-01  1.009e+01  
 GE3    -3.889301e+04  -1.223326e+04  4.702e-03  9.970e+00  
 GE4    -3.889118e+04  1.832726e+00   2.882e-03  9.795e+00  
 GE5    -3.886013e+04  3.104656e+01   8.977e-05  9.956e+00  
 GE6    -3.885985e+04  2.833305e-01   2.139e-05  9.815e+00  
 GE7    -3.885977e+04  8.047848e-02   3.919e-06  1.006e+01  
 GE8    -3.885977e+04  -1.648113e-03  1.594e-08  9.889e+00 
"

Test case is 
[Hf_HCP.zip](https://github.com/deepmodeling/abacus-develop/files/10402086/Hf_HCP.zip)

### Expected behavior

Different orbital files should lead to similar energy, as well as similar forces and stresses.

**Comment by dyzheng** [comment] 2023-05-08 05:19
@jinzx10 Hello, can you test this Issue? I don't know whether the orbital file is wrong or the calculation of ABACUS has problem.

**Comment by jinzx10** [comment] 2023-05-08 15:01
> @jinzx10 Hello, can you test this Issue? I don't know whether the orbital file is wrong or the calculation of ABACUS has problem.

I think this issue is somewhat similar to https://github.com/abacusmodeling/abacus-develop/issues/212 that the erratic total energies with TZDP-7/8/9 basis sets come from inappropriate energy cutoffs for LCAO's 1-D integration (which, on the other hand, might also be understood as unsatisfactory basis quality). 

I changed the calculation to 'scf' and set 'lcao_ecut' to 400. The resulting total energies all look very reasonable:
![etot](https://user-images.githubusercontent.com/26805483/236855190-fc993ec4-e07f-4cb7-8b84-7c0af931e11b.png)

Various orbitals in the TZDP-7/8/9 basis sets could be the cause of the problem. Roughly speaking, orbitals with higher angular momentum have poorer quality and larger trucation error. Below are the plots of several problematic orbitals. The real-space function chi(r) as well as the kinetic energy integrand k^4*chi(k) are plotted. The k-space plots suggest that lcao_ecut=100 Ry (as marked by the red dotted line) would lead to huge error in the kinetic energy matrix elements.

![orb-g-1](https://user-images.githubusercontent.com/26805483/236857167-dc8179e3-5b0e-448b-94db-dc5d00f0b609.png)


![orb-g-2](https://user-images.githubusercontent.com/26805483/236857184-41f97283-8b84-4949-ad60-eb700c5f04bc.png)


![orb-f-2](https://user-images.githubusercontent.com/26805483/236857219-6ebe084a-09dc-4588-a749-0a226f2ec8ad.png)


![orb-f-3](https://user-images.githubusercontent.com/26805483/236857239-c2b8063f-6d76-4abe-9c2c-7853c50344f1.png)


![orb-d-1](https://user-images.githubusercontent.com/26805483/236857264-4c85e2f3-f841-46f2-abf6-57411d463ef0.png)


![orb-d-2](https://user-images.githubusercontent.com/26805483/236857283-7740cd16-252c-4ea3-887f-95a5b27a4d58.png)


![orb-d-3](https://user-images.githubusercontent.com/26805483/236857305-91fddd7d-4f15-4fb7-a852-57e634cdb0dc.png)

**Comment by LiuXiaohui123321** [comment] 2023-05-16 09:01
@wszhang Can you take a look at this problem? It looks like the quality of TZDP orbitals with shorter Rcut is bad.

**Comment by wszhang** [comment] 2023-05-18 09:49
I think choosing a larger energy cutoff (110Ry 120Ry ... ) should solve this problem, the more fundamental solution shown above is being tested.

**Comment by hongriTianqi** [comment] 2023-09-09 06:49
- [ ] Review and understand the proposed feature and its importance.
- [ ] Research on the existing solutions and relevant research articles/resources.
- [ ] Discuss with the team to evaluate the feasibility of implementing the feature.
- [ ] Create a design document outlining the proposed solution and implementation details.
- [ ] Get feedback from the team and stakeholders on the design document.
- [ ] Develop the feature following the agreed design.
- [ ] Write unit tests and integration tests for the feature.
- [ ] Update the documentation to include the new feature.
- [ ] Perform code review and address any issues.
- [ ] Merge the feature into the main branch.
- [ ] Monitor for any issues or bugs reported by users after the feature is released.
- [ ] Address any issues or bugs reported by users and continuously improve the feature.

**Comment by kirk0830** [comment] 2024-04-09 03:14
After a relatively long period, @jinzx10 and I have found this issue may result from:  
- the set of bands selected for fitting/learning is limited, **mostly only occupied bands would be selected, however for polarization orbitals with higher angular momentum, conventionally they are unoccupied**. Therefore coefficients of Spherical Bessel functions of them are not efficiently optimized, or say orbitals with high angular momentum will not be sensed by Spillage function.
- the overlap matrix between Spherical Bessel functions and truncated one, indiced by (G, q) is **highly ill-conditioned**, this may bring ill-optimization on Spillage.
![image](https://github.com/deepmodeling/abacus-develop/assets/67682086/697320a4-d23d-4430-a2b2-ae84a0a3daae)
- **the estimation on number of spherical bessel functions needed is, somehow wrong**.
- **there are significant numerical error when evaluating<jY|jY>** that is needed for calculating Spillage, which has been mentioned in issue #3618.

On the other hand the figure posted above implies the high-frequency oscillation seems really unphysical. One can remove them by solving following linear equation:
![image](https://github.com/deepmodeling/abacus-develop/assets/67682086/34c6ebca-78af-4b2b-93e7-0bd2e3c1795b)
or in matrix form:
![image](https://github.com/deepmodeling/abacus-develop/assets/67682086/a5a1d949-9c36-460d-9a10-9e7eefa00b30)
Then after zeroing some c(s) of high-frequency components, one can get somehow more satisfying-looking profiles:
![screenshot-20240407-150025](https://github.com/deepmodeling/abacus-develop/assets/67682086/33a9ed12-ce7e-493b-8778-530434518968)

a simialr issue has been closed in some previous time: #2695

**Closed as completed by kirk0830** 2024-04-09 03:14 UTC
