### ISSUE TITLE
Discrepancy between gamma_only=1 and gamma_only =0 with k-111 

### ISSUE THREAD

**Issue by maki49** [deepmodeling/abacus-develop#2864] opened 2023-08-25 06:32 UTC
### Describe the bug

See the logs in the .zip file. "gamma" means `gamma_only 1` in INPUT file, while "k111" means `gamma_only 0` with such a KPT file: 
```
K_POINTS
0
Gamma
1 1 1 0 0 0
```
[1Si-spin2.zip](https://github.com/deepmodeling/abacus-develop/files/12436247/1Si-spin2.zip)
(An nspin=2 case with smearing_sigma=1e-20 provided in https://github.com/deepmodeling/abacus-develop/issues/2853 )

**Comment by hongriTianqi** [comment] 2023-09-08 04:38
- [x] Verify the issue is not a duplicate.
- [x] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by hongriTianqi** [comment] 2023-10-18 07:58
@maki49 What's the discrepancy?

**Comment by maki49** [comment] 2024-01-02 06:18
> @maki49 What's the discrepancy?
gamma_only can get converged but k-111 cannot, as the logs in the .zip file shows.

**Comment by WHUweiqingzhou** [comment] 2024-09-14 05:03
We tried v3.7.5, and found the result from gamma_only and k-111 is same.

**Closed as completed by WHUweiqingzhou** 2024-09-14 05:03 UTC
Labels: Bugs
