### ISSUE TITLE
Add accuracy tests for mathematical functions in two-center integral

### ISSUE THREAD

**Issue by jieli-matrix** [deepmodeling/abacus-develop#2837] opened 2023-08-16 06:48 UTC
### Describe Current Status and Possible Solution

Considering the numerical divergence phenomenon in the current calculation process of two-center integral, we suspect that this may be related to the accuracy and machine precision of the underlying mathematical functions involved. Therefore, we plan to conduct  accuracy and machine precision tests on the following functions:
1. Sphere Bessel Function of the First Kind
2. Sphere harmonics
3. Cubic Spline Interpolation
4. Polynomial Interpolation
5. Simpson Integral.
 
Accuracy tests will be done for 1. and 2., while machine precision tests will be done for 3., 4., and 5. The test platform includes GNU and Intel platforms with floating-point control options enabled or disabled.

**Comment by hongriTianqi** [comment] 2023-09-08 04:46
- [x] Understand the problem or question described by the user.
- [x] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [ ] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Closed as completed** 2023-09-21 07:39 UTC
