### ISSUE TITLE
Discrepancy between v3.1.3 and v3.1.4

### ISSUE THREAD

**Issue by wenfei-li** [deepmodeling/abacus-develop#2172] opened 2023-03-30 09:59 UTC
### Details

Lately I discovered the latest version of ABACUS does not reproduce earlier result on BaTiO3, and it seems that the discrepancy is already present at first SCF step, so presumably it has something to do with initial condition / basis set / eigensolver.
The discrepancy has been located between v3.1.3 and v3.1.4. Just want to make sure if this is expected behavior or a bug.
The input and output files are attached with this issue.
[BaTiO3.zip](https://github.com/deepmodeling/abacus-develop/files/11110229/BaTiO3.zip)

**Comment by mohanchen** [comment] 2023-04-13 06:26
close the symmetry first and see if the results are consistent, because the symmetry analysis is updated around this period

**Comment by wenfei-li** [comment] 2023-04-13 07:41
Symmetry is off for both cases

**Comment by maki49** [comment] 2023-04-13 11:47
I PR #1904 , I modified the bound of k-points from [0,1) to (-0.5, 0.5] in function `ibz_kpoints` according to vasp, maybe the small error come from this. 
The default value of `symmetry` is 0. Setting `symmetry` to -1 will this function not be called.

**Comment by mohanchen** [comment] 2023-04-26 08:28
This is expected due to the changes of the symmetry analysis code.

**Comment by wenfei-li** [comment] 2023-05-09 07:11
symmetry only explains half of the problem, the problem in issue seems not resolved yet

**Comment by wenfei-li** [comment] 2023-05-17 07:34
might have something to do with #1945

**Comment by wenfei-li** [comment] 2023-08-07 03:36
It seems we are not going to address this issue, so I'll just close it

**Comment by mohanchen** [comment] 2023-08-13 12:17
What do you mean by "seems", who are "we"?

**Comment by hongriTianqi** [comment] 2023-09-09 07:16
- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by dyzheng** [comment] 2024-01-02 06:12
I suggest to close this Issue, because that in ABACUS v3.5.0 we report the results of alloy systems calculated by PW base, the correctness is same as QE for current version. 
ABACUS version after v3.5.0 can be trusted for PW calculation.

**Closed as completed by dyzheng** 2024-01-02 06:12 UTC
Labels: Bugs
