### ISSUE TITLE
SCF calculation with SOC fails to converge.

### ISSUE THREAD

**Issue by jingan-181** [deepmodeling/abacus-develop#2290] opened 2023-04-22 03:32 UTC
### Describe the bug

Using ABACUS v3.2.0 to perform the self-consistent calculation of monolayer SnTe with SOC, the charge density failed converge. The cause of the problem is speculated that the total magnetic moment is not 0 when the electron iterates. I set all atomic magnetic moments to 0 in the STRU file. The SnTe should be a non-magnetic material.
[SnTe-scf.zip](https://github.com/deepmodeling/abacus-develop/files/11300167/SnTe-scf.zip)
![1](https://user-images.githubusercontent.com/78459531/233759927-ae071b4c-1d07-4433-8344-b56ffe77e74d.png)
![2](https://user-images.githubusercontent.com/78459531/233759930-beb5dc76-afeb-4c15-b063-ae9092f491cf.png)

**Comment by Satinelamp** [comment] 2023-04-24 14:16
Just out of curiosity, I did some tests.
Actually, if you do more electronic step iterations, the convergence of `DRHO` would get stuck to about `10-7`, which might be caused by the numerical error of `EDIFF`, as the log shows after the error of `DRHO` reach to `10-7`, the total energy oscillates at the scale of `10-12`. But usually, when the error of total energy reaches `10-7`, the error of `DRHO` also reaches `10-7`. This failure might be related to the numerical error caused by the `precision of floating point number`, which decides that the error of total energy couldn't be lower.

```
START CHARGE      : atomic
 DONE(11.7881    SEC) : INIT SCF
 ITER   ETOT(eV)       EDIFF(eV)      DRHO       TIME(s)    
 GE1    -9.991340e+03  0.000000e+00   2.934e-02  5.206e+00  
 GE2    -9.991425e+03  -8.482276e-02  1.101e-02  5.138e+00  
 GE3    -9.991420e+03  4.438911e-03   4.542e-03  5.085e+00  
 GE4    -9.991417e+03  3.527439e-03   2.514e-03  5.079e+00  
 GE5    -9.991414e+03  2.498785e-03   1.744e-03  5.101e+00  
 GE6    -9.991414e+03  3.131484e-04   1.136e-03  5.132e+00  
 GE7    -9.991414e+03  -1.932493e-05  8.682e-04  5.100e+00  
 GE8    -9.991414e+03  -6.721802e-05  7.221e-04  5.090e+00  
 GE9    -9.991414e+03  -1.373189e-04  6.538e-04  5.123e+00  
 GE10   -9.991414e+03  -1.333528e-04  5.884e-04  5.084e+00  
..........................
 GE1980 -9.991415e+03  1.113688e-10   4.777e-07  5.081e+00  
 GE1981 -9.991415e+03  1.546789e-12   3.736e-07  5.077e+00  
 GE1982 -9.991415e+03  5.444697e-10   4.739e-07  5.074e+00  
 GE1983 -9.991415e+03  -3.093578e-12  5.017e-07  5.077e+00  
 GE1984 -9.991415e+03  -3.712293e-11  5.461e-07  5.081e+00  
 GE1985 -9.991415e+03  -4.547559e-10  4.878e-07  5.077e+00  
 GE1986 -9.991415e+03  5.645779e-10   5.147e-07  5.080e+00  
 GE1987 -9.991415e+03  -4.563027e-10  4.475e-07  5.085e+00  
 GE1988 -9.991415e+03  1.036348e-10   4.992e-07  5.086e+00  
 GE1989 -9.991415e+03  4.021651e-11   5.128e-07  5.077e+00  
 GE1990 -9.991415e+03  -2.877027e-10  4.021e-07  5.084e+00  
 GE1991 -9.991415e+03  9.435412e-11   3.404e-07  5.114e+00  
 GE1992 -9.991415e+03  2.026293e-10   5.650e-07  5.094e+00  
 GE1993 -9.991415e+03  -3.588550e-10  3.698e-07  5.083e+00  
 GE1994 -9.991415e+03  1.577725e-10   5.102e-07  5.079e+00  
 GE1995 -9.991415e+03  8.971375e-11   4.855e-07  5.079e+00  
 GE1996 -9.991415e+03  2.768752e-10   4.869e-07  5.082e+00  
 GE1997 -9.991415e+03  -3.573082e-10  4.130e-07  5.118e+00  
 GE1998 -9.991415e+03  3.201853e-10   5.453e-07  5.101e+00  
 GE1999 -9.991415e+03  -8.197981e-11  5.451e-07  5.120e+00  
 GE2000 -9.991415e+03  -1.670532e-10  4.134e-07  5.106e+00  
 !! CONVERGENCE HAS NOT BEEN ACHIEVED !!
```

Here is the log if I run 2000 iterations.
[log.txt](https://github.com/deepmodeling/abacus-develop/files/11311311/log.txt)


Here is another successful `relax` type of calculation.
```
 STEP OF RELAXATION : 74
 -------------------------------------------
 DONE(1.301e+03  SEC) : INIT SCF
 ITER   ETOT(eV)       EDIFF(eV)      DRHO       TIME(s)    
 GE1    -2.239390e+04  0.000000e+00   3.875e-04  1.174e+00  
 GE2    -2.239388e+04  1.832054e-02   9.978e-03  1.235e+00  
 GE3    -2.239390e+04  -1.857396e-02  2.176e-03  1.235e+00  
 GE4    -2.239391e+04  -1.892934e-03  1.152e-04  1.236e+00  
 GE5    -2.239391e+04  -8.096508e-06  4.857e-05  1.236e+00  
 GE6    -2.239391e+04  -5.891316e-07  4.472e-05  1.236e+00  
 GE7    -2.239391e+04  2.479162e-07   3.807e-05  1.235e+00  
 GE8    -2.239391e+04  2.609154e-07   2.487e-05  1.239e+00  
 GE9    -2.239391e+04  6.691130e-07   7.984e-06  1.115e+00  
 LARGEST GRAD (eV/A)  : 1.641e-02
 -------------------------------------------
 STEP OF RELAXATION : 75
 -------------------------------------------
 DONE(1.315e+03  SEC) : INIT SCF
 ITER   ETOT(eV)       EDIFF(eV)      DRHO       TIME(s)    
 GE1    -2.239390e+04  0.000000e+00   2.420e-04  1.174e+00  
 GE2    -2.239390e+04  4.234243e-03   3.071e-03  1.237e+00  
 GE3    -2.239390e+04  -3.436078e-03  1.868e-03  1.237e+00  
 GE4    -2.239391e+04  -1.362326e-03  7.110e-05  1.235e+00  
 GE5    -2.239391e+04  -3.425453e-06  2.836e-05  1.235e+00  
 GE6    -2.239391e+04  -2.739889e-07  2.937e-05  1.237e+00  
 GE7    -2.239391e+04  2.339735e-07   2.278e-05  1.235e+00  
 GE8    -2.239391e+04  1.194795e-06   9.541e-06  1.113e+00  
 LARGEST GRAD (eV/A)  : 8.838e-03

```

**Comment by Satinelamp** [comment] 2023-04-26 19:04
the test in https://github.com/deepmodeling/abacus-develop/issues/1945 shows the difference of `etot` between different repeated simulations is about `10^-10`.

**Comment by jingan-181** [comment] 2023-05-15 02:23
Using HSE+SOC calculation will not encounter this problem.

[HSE-scf.zip](https://github.com/deepmodeling/abacus-develop/files/11473680/HSE-scf.zip)

**Comment by dyzheng** [comment] 2023-05-15 16:44
I have checked this case of SnTe, HR of nonlocal part is not Hermitian for local matrix, which will lead to non-Hermitian for HK. This is not expected behavier, but coefficient of effective D is right with formula. I will check the case of HSE to double check this problem.

**Comment by wenfei-li** [comment] 2023-05-17 07:32
I'll have a look into this issue

**Comment by wenfei-li** [comment] 2023-05-29 09:45
first of all, I checked and the hamiltonian matrix is hermitian; I also wrote a separate script for calculating the soc vnl matrix, and the result matches that from ABACUS; finally, I tried checking out previous versions of ABACUS, and the magnetic moment has always been present
so it seems to me that this is not a bug, rather it is because ABACUS has poor convergence algorithm for nspin = 2 and 4

**Comment by wenfei-li** [comment] 2023-05-29 11:57
btw the code for preparing the nonlocal part of soc pseudopotential in ABACUS is rather difficult to understand imo (lack of comment, strange way of arranging the indexes, etc.), I attach my script here. It does the equivalent of generating f_coeff in ABACUS. 
[soc.zip](https://github.com/deepmodeling/abacus-develop/files/11591510/soc.zip)

**Comment by wenfei-li** [comment] 2023-05-30 10:51
see also https://github.com/deepmodeling/abacus-develop/issues/515

**Comment by hongriTianqi** [comment] 2023-09-09 08:09
- [x] Verify the issue is not a duplicate.
- [x] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by hongriTianqi** [comment] 2023-10-25 08:25
@hongriTianqi Do you have more examples on this topic?

**Comment by jingan-181** [comment] 2023-10-25 08:44
I don't have any more examples because I've only encountered this issue with this material.

**Comment by hongriTianqi** [comment] 2023-11-09 05:11
@jingan-181 @dyzheng  This case is successful now if you use the newest code:
<img width="554" alt="tt" src="https://github.com/deepmodeling/abacus-develop/assets/18049272/fd80a757-32f3-47cc-b501-a61a1f06c2ef">

**Comment by hongriTianqi** [comment] 2023-11-09 05:19
Although converged, there are still magnetic moments:
[running_scf.log](https://github.com/deepmodeling/abacus-develop/files/13303991/running_scf.log)
<img width="759" alt="pp" src="https://github.com/deepmodeling/abacus-develop/assets/18049272/03ee4525-c039-4f3e-861e-3d326f483536">

**Comment by hongriTianqi** [comment] 2023-11-29 06:55
@jingan-181 As the absolute magnetism that appears is very small, could you please test this case again to see if the current code can deal with this system now?

**Comment by hongriTianqi** [comment] 2023-12-26 07:39
This will be closed as we have not received response for a long time.

**Comment by hongriTianqi** [comment] 2024-01-17 07:02
To update, the absolute magnetism increased a bit after PR #3503:
the new results are:
```
 LCAO ALGORITHM --------------- ION=   1  ELEC= 100--------------------------------
total magnetism (Bohr mag/cell) 9.95524e-06     -2.36304e-05    0.000777806
       absolute magnetism (Bohr mag/cell) = 0.102571
```
as can be seen https://labs.dp.tech/projects/abacustest/?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fjob-abacustest-v0.3.90-0c8e71

**Comment by WHUweiqingzhou** [comment] 2024-02-22 08:18
@jingan-181 
Do you have more comments about this issue?

**Comment by jingan-181** [comment] 2024-02-22 09:23
I think the absolute magnetism of SnTe should be 0. Because when HSE+SOC is used for calculation, the absolute magnetism of each electron step is about 7.94936e-15, and the self-consistency of PBE only requires 25 steps.

![SnTe_mag](https://github.com/deepmodeling/abacus-develop/assets/78459531/074ae7aa-fe38-4e5f-b7b8-c655dfbe1eed)

**Comment by jingan-181** [comment] 2024-02-22 09:31
This is my HSE+SOC INPUT file, other files remain the same.

[INPUT.txt](https://github.com/deepmodeling/abacus-develop/files/14371860/INPUT.txt)

**Comment by hongriTianqi** [comment] 2024-02-29 08:32
To update, the problem still exits at 2024-2-29:
Commit: 67474ff (Wed Feb 28 11:27:13 2024 +0800)
```
LCAO ALGORITHM --------------- ION=   1  ELEC= 100--------------------------------
total magnetism (Bohr mag/cell) 9.95078e-06     -2.34459e-05    0.000777786
       absolute magnetism (Bohr mag/cell) = 0.102539
```

**Comment by hongriTianqi** [comment] 2024-07-25 08:35
[SnTe_results.tar.gz](https://github.com/user-attachments/files/16373029/SnTe_results.tar.gz)
This issue is missing in new version 3.7.1

firstly, it is converged in 37 steps:
```
<< Start SCF iteration.
 ITER     TMAGX      TMAGY      TMAGZ       AMAG        ETOT/eV          EDIFF/eV         DRHO     TIME/s
 GE1     -1.59e-07   3.58e-09   8.30e-03   1.36e-01  -9.99066005e+03   0.00000000e+00   1.4353e-01  12.37
 GE2      1.30e-07  -3.72e-09  -6.23e-03   4.89e-02  -9.99135239e+03  -6.92336394e-01   7.9163e-02  12.08
 GE3     -4.77e-05  -5.31e-05   8.96e-05   5.57e-03  -9.99134739e+03   5.00449258e-03   7.6237e-03  12.16
 GE4     -1.36e-05   3.28e-06  -1.17e-04   4.73e-03  -9.99134534e+03   2.04523153e-03   3.2845e-03  12.06
 GE5      2.07e-05   1.73e-05   6.32e-05   2.34e-03  -9.99134429e+03   1.04776971e-03   2.1900e-03  12.20
 GE6      8.57e-06   3.80e-06  -4.20e-06   7.64e-04  -9.99134247e+03   1.82376360e-03   1.5721e-03  12.04
 GE7     -6.31e-06  -3.37e-06  -1.42e-07   5.91e-04  -9.99134164e+03   8.31465188e-04   1.1178e-03  12.17
 GE8      8.86e-07   2.11e-06   1.51e-06   2.19e-04  -9.99134159e+03   5.07322760e-05   7.7183e-04  12.19
 GE9     -3.39e-09  -9.53e-07  -8.07e-07   3.33e-04  -9.99134176e+03  -1.71445575e-04   5.5172e-04  12.24
 GE10     1.38e-06  -4.92e-08   1.89e-06   2.99e-04  -9.99134200e+03  -2.37733156e-04   4.0046e-04  12.09
 GE11    -3.80e-06  -3.92e-06  -9.17e-07   2.95e-04  -9.99134221e+03  -2.10417070e-04   2.6943e-04  12.14
 GE12    -8.80e-06  -4.99e-06   2.64e-06   3.87e-04  -9.99134230e+03  -8.86529151e-05   1.8800e-04  12.16
 GE13     3.66e-07   1.12e-06   7.99e-07   2.83e-04  -9.99134237e+03  -7.81214676e-05   1.5059e-04  12.05
 GE14     8.83e-06   5.13e-06  -1.54e-06   4.65e-04  -9.99134241e+03  -4.04837857e-05   1.1918e-04  12.06
 GE15     1.12e-05   7.71e-06  -1.88e-06   5.29e-04  -9.99134244e+03  -2.23747282e-05   1.0267e-04  12.20
 GE16     8.58e-06   7.69e-06  -3.25e-06   5.16e-04  -9.99134247e+03  -3.12712339e-05   9.2161e-05  12.22
 GE17     2.06e-06   1.50e-06  -1.87e-06   1.47e-04  -9.99134251e+03  -4.24046777e-05   7.4398e-05  12.21
 GE18    -5.51e-07  -6.16e-07  -1.73e-06   2.03e-04  -9.99134253e+03  -1.72872270e-05   5.4662e-05  12.08
 GE19    -2.84e-07   2.20e-08   4.12e-08   1.11e-04  -9.99134255e+03  -1.89116398e-05   4.2930e-05  12.06
 GE20     4.72e-07   2.81e-07  -3.94e-08   6.70e-05  -9.99134257e+03  -2.49131029e-05   3.3173e-05  12.04
 GE21     6.79e-07   3.31e-07   2.48e-07   4.38e-05  -9.99134258e+03  -1.12284197e-05   1.9825e-05  12.07
 GE22     1.95e-07   1.38e-07   5.40e-09   1.95e-05  -9.99134260e+03  -1.82654347e-05   1.4607e-05  12.06
 GE23     2.63e-08   2.39e-08  -5.94e-09   1.14e-05  -9.99134261e+03  -5.66405591e-06   8.6649e-06  12.07
 GE24     3.18e-08   2.33e-08   2.69e-09   5.72e-06  -9.99134261e+03  -1.98673727e-06   6.5072e-06  12.07
 GE25    -7.24e-09  -1.39e-08  -7.38e-09   5.51e-06  -9.99134261e+03   7.35674399e-07   4.2844e-06  12.07
 GE26    -3.02e-08  -2.30e-08  -1.66e-10   4.03e-06  -9.99134261e+03   2.28307571e-07   2.9288e-06  12.09
 GE27    -1.34e-08  -9.03e-09  -5.77e-10   1.59e-06  -9.99134261e+03  -2.89971852e-07   1.7606e-06  12.07
 GE28     1.13e-08   5.35e-09  -1.36e-10   5.41e-07  -9.99134261e+03   1.78143664e-08   1.3506e-06  12.10
 GE29     3.00e-09   1.86e-09  -5.68e-11   2.03e-07  -9.99134261e+03  -1.50040059e-07   8.5936e-07  12.10
 GE30    -2.06e-11   4.22e-11   1.24e-10   8.26e-08  -9.99134261e+03  -9.25381856e-08   4.1514e-07  12.07
 GE31    -1.40e-10  -8.96e-11  -8.07e-11   3.32e-08  -9.99134261e+03  -1.07019222e-07   3.3702e-07  12.04
 GE32    -3.80e-10  -1.19e-10   6.51e-11   3.53e-08  -9.99134261e+03  -9.20710554e-08   2.4898e-07  12.14
 GE33     4.14e-11   2.84e-11  -1.17e-10   2.05e-08  -9.99134261e+03  -6.45428554e-08   1.6637e-07  12.14
 GE34    -4.18e-11  -4.67e-11   2.89e-11   1.38e-08  -9.99134261e+03  -3.97107084e-08   9.6226e-08  12.16
 GE35     4.21e-11   4.09e-11  -1.08e-11   1.06e-08  -9.99134261e+03  -1.51631704e-08   4.5085e-08  12.17
 GE36    -2.99e-11  -7.04e-12   2.65e-11   5.00e-09  -9.99134261e+03  -5.19102315e-09   1.7478e-08  12.12
 GE37     5.09e-13  -1.81e-12  -1.14e-11   1.50e-09  -9.99134261e+03   1.45088788e-09   7.0389e-09  12.16
```

secondly, the total mag is very small now, as expected:
```
 LCAO ALGORITHM --------------- ION=   1  ELEC=  37--------------------------------
total magnetism (Bohr mag/cell) 5.08607e-13     -1.80646e-12    -1.13878e-11
       absolute magnetism (Bohr mag/cell) = 1.50415e-09

 Density error is 7.03893983503e-09
```

**Closed as completed** 2024-07-25 08:36 UTC
Labels: collinear/non-collinear/SOC
