### ISSUE TITLE
fail to install the latest develop version

### ISSUE THREAD

**Issue by Satinelamp** [deepmodeling/abacus-develop#4657] opened 2024-07-11 18:25 UTC
### Describe the bug

I try to install the latest develop version, but got the following error:
```
[100%] Linking CXX executable abacus
icpc: command line warning #10148: option '-Wno-tautological-constant-compare' not supported
[100%] Built target operator_ks_pw
ld: source/module_hamilt_lcao/module_dftu/CMakeFiles/dftu.dir/dftu_hamilt.cpp.o: undefined reference to symbol 'pdtran_'
/home/fuyiwei/intel/oneapi/mkl/2022.0.2/lib/intel64/libmkl_scalapack_lp64.so.2: error adding symbols: DSO missing from command line
gmake[2]: *** [abacus] Error 1
gmake[1]: *** [CMakeFiles/abacus.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
[100%] Built target operator_ks_lcao
gmake: *** [all] Error 2

```
when I install the 3.7.0 version, it works fine.

### Environment

LSB Version:	:core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.5.1804 (Core) 
Release:	7.5.1804
Codename:	Core

I am using the following command to install :

```
cmake:
wget https://github.com/Kitware/CMake/releases/download/v3.25.1/cmake-3.25.1-linux-x86_64.tar.gz
tar -zxvf cmake-3.25.1-linux-x86_64.tar.gz
export PATH=/home/alma/software/cmake-3.25.1-linux-x86_64/bin:${PATH}

Intel OneAPI:
wget https://registrationcenter-download.intel.com/akdlm/irc_nas/18236/l_BaseKit_p_2021.4.0.3422_offline.sh
bash l_BaseKit_p_2021.4.0.3422_offline.sh
wget https://registrationcenter-download.intel.com/akdlm/irc_nas/18211/l_HPCKit_p_2021.4.0.3347_offline.sh
bash l_HPCKit_p_2021.4.0.3347_offline.sh
source ~/intel/oneapi/setvars.sh

ELPA:
下载ELPA
tar xzf elpa-2021.05.002.tar.gz
cd elpa-2021.05.002 
mkdir build 
cd build 
CC=mpiicc CXX=mpiicpc FC=mpiifort ../configure --enable-openmp --prefix=/home/alma/software/elpa_install FCFLAGS="-qmkl=cluster"
make -j9 
make install
ln -s /home/alma/software/elpa_install/include/elpa-2021.05.002/elpa /home/alma/software/elpa_install/include/ 

Cereal:
git clone https://github.com/USCiLab/cereal.git \

LibXC:
tar xzf libxc-5.2.3.tar.gz
cd libxc-5.2.3
mkdir build
cmake -B build -DCMAKE_C_COMPILER=mpiicc -DCMAKE_INSTALL_PREFIX=/home/fuyiwei/software/libxc_install -DBUILD_TESTING=OFF
cmake --build build
cmake --install build

ABACUS:
cd abacus-develop

cmake -DCMAKE_CXX_COMPILER=mpiicpc -DMPI_CXX_COMPILER=mpiicpc -B build -DCMAKE_INSTALL_PREFIX=~/software/abacus_install -DELPA_DIR=~/software/elpa_install -DCEREAL_INCLUDE_DIR=~/software/cereal/include -DLibxc_DIR=/home/fuyiwei/software/libxc_install
```

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by QuantumMisaka** [comment] 2024-07-12 02:11
@Satinelamp Have you tried toolchain method ?

**Comment by caic99** [comment] 2024-07-12 02:52
Hi @Satinelamp , 
Would you attach your building log? Thanks.

**Comment by caic99** [comment] 2024-07-12 03:21
I found that when using `icpc` with Intel oneAPI 2022 and before, the `MKL::MKL_SCALAPACK` library is not found properly. I'll try to submit a PR adding a fallback.

**Comment by caic99** [comment] 2024-07-12 03:38
Hi @Qianruipku @Satinelamp ,
I've located the problem and proposed changes in #4663 . Since I don't have the exact environment to reproduce the error, would you mind helping me test if the PR works? Thanks.

**Comment by Satinelamp** [comment] 2024-07-12 05:07
@caic99 ， how should merge this PR on my PC? any tutorial about how to use git?

**Comment by Satinelamp** [comment] 2024-07-12 05:12
> Hi @Qianruipku @Satinelamp , I've located the problem and proposed changes in #4663 . Since I don't have the exact environment to reproduce the error, would you mind helping me test if the PR works? Thanks.

I tried this PR, the error still exists, here is the build.log

[build.log](https://github.com/user-attachments/files/16188911/build.log)

**Comment by Satinelamp** [comment] 2024-07-12 05:14
> @Satinelamp Have you tried toolchain method ?

I haven't, I followed the guide [here](https://github.com/deepmodeling/abacus-develop/wiki/Building-and-Running-ABACUS)

**Comment by caic99** [comment] 2024-07-12 05:35
@Satinelamp And also configuration log, please

**Comment by Satinelamp** [comment] 2024-07-12 05:40
```
cmake -DCMAKE_CXX_COMPILER=mpiicpc -DMPI_CXX_COMPILER=mpiicpc -B build -DCMAKE_INSTALL_PREFIX=~/software/abacus_install -DELPA_DIR=~/software/elpa_install -DCEREAL_INCLUDE_DIR=~/software/cereal/include -DLibxc_DIR=/home/fuyiwei/software/libxc_install
```

> @Satinelamp And also configuration log, please

**Comment by caic99** [comment] 2024-07-12 05:49
@Satinelamp Sorry but I mean the screen output

**Comment by Satinelamp** [comment] 2024-07-12 05:52
> @Satinelamp Sorry but I mean the screen output

```
abacus-develop]$ cmake -DCMAKE_CXX_COMPILER=mpiicpc -DMPI_CXX_COMPILER=mpiicpc -B build -DCMAKE_INSTALL_PREFIX=~/software/abacus_install -DELPA_DIR=~/software/elpa_install -DCEREAL_INCLUDE_DIR=~/software/cereal/include -DLibxc_DIR=/home/fuyiwei/software/libxc_install 
-- The CXX compiler identification is Intel 2021.5.0.20211109
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /home/fuyiwei/intel/oneapi/mpi/2021.5.1/bin/mpiicpc - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/bin/git (found version "1.8.3.1") 
-- Found git: attempting to get commit info...
-- Current commit hash: 81c6845
-- Last commit date: Fri Jul 12 11:36:16 2024 +0800
-- Found Cereal: /home/fuyiwei/software/cereal/include  
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.27.1") 
-- Found ELPA: /home/fuyiwei/software/elpa_install/lib/libelpa.so  
-- Performing Test ELPA_VERSION_SATISFIES
-- Performing Test ELPA_VERSION_SATISFIES - Success
-- Found MPI_CXX: /home/fuyiwei/intel/oneapi/mpi/2021.5.1/bin/mpiicpc (found version "3.1") 
-- Found MPI: TRUE (found version "3.1")  
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Found OpenMP_CXX: -qopenmp (found version "5.0") 
-- Found OpenMP: TRUE (found version "5.0")  
-- Looking for a CUDA compiler
-- Looking for a CUDA compiler - NOTFOUND
-- MKL_ARCH: None, set to ` intel64` by default
-- MKL_LINK: None, set to ` dynamic` by default
-- MKL_INTERFACE_FULL: intel_lp64
-- MKL_THREADING: None, set to ` intel_thread` by default
-- MKL_MPI: None, set to ` intelmpi` by default
-- Found MKL: intelmpi  
-- Found MKL: /home/fuyiwei/intel/oneapi/mkl/2022.0.2  
-- Found MKL: /home/fuyiwei/intel/oneapi/mkl/2022.0.2/lib/intel64/libmkl_intel_lp64.so  
-- Found MKL: /home/fuyiwei/intel/oneapi/mkl/2022.0.2/lib/intel64/libmkl_core.so  
-- Found MKL: /home/fuyiwei/intel/oneapi/mkl/2022.0.2/lib/intel64/libmkl_intel_thread.so  
-- Found MKL: /home/fuyiwei/intel/oneapi/compiler/latest/linux/compiler/lib/intel64/libiomp5.so  
-- Checking for one of the modules 'libxc'
-- Found Libxc: /home/fuyiwei/software/libxc_install/lib64/libxc.a  
-- Found Libxc: version 6.2.0
-- Configuring done
-- Generating done
-- Build files have been written to: /home/fuyiwei/software/abacus-develop/build

```

**Comment by caic99** [comment] 2024-07-12 06:36
@Satinelamp I noticed that the `libmkl_scalapack_lp64.so` is not present on the library list. However, this should have been fixed in the PR.
I've added the message output if Scalapack found in the latest commit, and should you pull the latest branch of PR and try again.

**Comment by Qianruipku** [comment] 2024-07-12 07:21
> Hi @Qianruipku @Satinelamp , I've located the problem and proposed changes in #4663 . Since I don't have the exact environment to reproduce the error, would you mind helping me test if the PR works? Thanks.

@caic99  Still no work
![image](https://github.com/user-attachments/assets/e281f010-6b99-42ef-b431-dc66357fd724)
![image](https://github.com/user-attachments/assets/d326781e-4063-49a2-918a-b6f5a7c70f13)

**Comment by Qianruipku** [comment] 2024-07-12 07:25
Both icpc and icpx : undefined reference to 'pdtran_'

**Comment by Qianruipku** [comment] 2024-07-12 07:31
previous version works:
![image](https://github.com/user-attachments/assets/833c0760-260a-40d2-a206-5b498a549d95)
current version does not work:
![image](https://github.com/user-attachments/assets/4340e77a-f903-422d-9f23-91c162833417)

**Comment by caic99** [comment] 2024-07-12 07:32
@Qianruipku Would you attach your cmake configure output? Thanks

**Comment by Qianruipku** [comment] 2024-07-12 07:34
![image](https://github.com/user-attachments/assets/8a50166c-1b49-4d03-ab7e-463879da2098)

**Comment by caic99** [comment] 2024-07-12 07:46
@Qianruipku It seems that scalapack library is found... I've update the config, and please try again.

**Comment by Qianruipku** [comment] 2024-07-12 08:09
@caic99  It works! Good job!

**Comment by caic99** [comment] 2024-07-12 08:11
> @caic99 It works! Good job!

Finally! @Qianruipku Please run some test cases to ensure the correctness, and also approve the PR.
It seems that the default behavior changes across MKL versions.

**Comment by Satinelamp** [comment] 2024-07-12 08:14
> @Qianruipku It seems that scalapack library is found... I've update the config, and please try again.

works for me, too. Thanks a lot.

**Closed as completed** 2024-07-12 08:14 UTC
Labels: Compile & CICD & Docs & Dependencies
