### ISSUE TITLE
run /examples/md/lcao_gammaonly_Si8 failed

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#2953] opened 2023-09-15 00:38 UTC
### Describe the bug

Run the /examples/md/lcao_gammaonly_Si8 INPUT_4 failed, the error message is:
```
initial strain rate = -1.158e-06    msst_tscale = 1.000e-02
 ------------------------------------------------------------------------------------------------
 Energy (Ry)         Potential (Ry)      Kinetic (Ry)        Temperature (K)     Pressure (kbar)     
 -6.215e+01          -6.217e+01          1.975e-02           2.970e+02           1.084e+02           
 ------------------------------------------------------------------------------------------------
 -------------------------------------------
 STEP OF MOLECULAR DYNAMICS : 1
 -------------------------------------------
 
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
                         NOTICE                           
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 
 the movement of atom is larger than the length of cell.
 CHECK IN FILE : OUT.Si_msst/warning.log
 
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
                         NOTICE                           
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```

And the error message in OUT.Si_msst/warning.log is:
```
 it=1 ia=1
d=0.000325142114415222 0.999913549808725 -1740540.63529629
 Ions_Move_Basic::move_ions  warning : the movement of atom is larger than the length of cell.
```
where d is the move length in direct coord type.

### Task list for Issue attackers

- [x] Verify the issue is not a duplicate.
- [x] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by pxlxingliang** [comment] 2023-09-15 00:42
This fail is occurred since #2904 merged.

**Comment by jinzx10** [comment] 2023-09-18 09:20
@pxlxingliang and I performed some tests based on commit #2882 (adf2d521a252ae82f9a4b1924b825d777a2a823b), which was merged before #2904 . We tried various compiler options and/or using printf/cout to output some intermediate results. The tests were performed independently, and we observed the same curious outcome as below:

1. adding -fp-model=strict --> error as shown in the original post ("the movement of atom is larger than the length of cell.")
2. adding -fp-model=strict, adding a few printf & cout to MSST::propagete_vel() (see below) --> run normally (surprise!)
3. same as 2, but comment out the line with "std::cout" --> error as shown in the original post (more surprise!)
4. code modification same as 2, but changing -fp-model=strict to -fp-model=precise --> run normally
5. code modification same as 3, but changing -fp-model=strict to -fp-model=precise --> segmentation fault, some normal floating number arithmetics produce nan (even more surprise!)
6. adding -fp-model=strict, changing -O3 to  -O1 --> run normally

From test 1 I think we can conclude that the problem is introduced in #2927 (compiler option change) instead of #2904 (two-center integral algorithmic change). However, this is very curious since #2927 merely changes the compiler flag, and the change (adding -fp-model=strict) is supposed to make the calculation safer, not the reverse.

The outcomes from test 2-5 are even more curious; the code behaves differently by adding a few printf/cout. With -fp-model=precise, some ordinary floating-point arithmetic (only plus, minus & multiplication) can even yield nan. 

I did a few more tests on my local machine and bohrium. None of them can reproduce the error; they all run normally. This seems to be an issue only reproducible within the environment set up by Dockerfile.intel. I tend to think there's either some latent undefined behavior in our code, or some problem with the environment itself. But either way, detecting such bug is beyond my capabiliy. I suggest this issue be transfered to some more experienced people. @caic99 @dyzheng @baixiaokuang 

code modification (adding printf & cout) to make it work:
```cpp
void MSST::propagate_vel()
{
    if (mdp.my_rank == 0)
    {
        const int sd = mdp.msst_direction;
        const double dthalf = 0.5 * mdp.md_dt;
        const double fac = mdp.msst_vis * pow(omega[sd], 2) / (vsum * ucell.omega);

        for (int i = 0; i < ucell.nat; ++i)
        {
            ModuleBase::Vector3<double> const_C = force[i] / allmass[i];
            ModuleBase::Vector3<double> const_D;
            const_D.set(fac / allmass[i], fac / allmass[i], fac / allmass[i]);
	    printf("const_D = % 18.12e   % 18.12e   % 18.12e\n", const_D[0], const_D[1], const_D[2]);
            const_D[sd] -= 2 * omega[sd] / ucell.omega;
	    printf("const_D = % 18.12e   % 18.12e   % 18.12e\n", const_D[0], const_D[1], const_D[2]);

            for (int k = 0; k < 3; ++k)
            {
                if (fabs(dthalf * const_D[k]) > 1e-6)
                {
                    double expd = exp(dthalf * const_D[k]);
		    printf("if: i = %i   k = %i   before: v = % 18.12e   expd = % 18.12e   c = % 18.12e   d = % 18.12e\n",
				    i, k, vel[i][k], expd, const_C[k], const_D[k]);
		    std::cout << const_C[k] << " " << const_D[k] << " " << vel[i][k] << " " << expd << std::endl;
                    vel[i][k] = expd * (const_C[k] + const_D[k] * vel[i][k] - const_C[k] / expd) / const_D[k];
		    printf("if:                 after : v = % 18.12e\n\n", vel[i][k]);
                }
                else
                {
		    printf("else: i = %i   k = %i   before: v = % 18.12e   dt/2 = % 18.12e   c = % 18.12e   d = % 18.12e\n",
				    i, k, vel[i][k], dthalf, const_C[k], const_D[k]);
                    vel[i][k]
                        += (const_C[k] + const_D[k] * vel[i][k]) * dthalf
                           + 0.5 * (const_D[k] * const_D[k] * vel[i][k] + const_C[k] * const_D[k]) * dthalf * dthalf;
		    printf("else:                 after : v = % 18.12e\n\n", vel[i][k]);
                }
            }
        }
    }

#ifdef __MPI
    MPI_Bcast(vel, ucell.nat * 3, MPI_DOUBLE, 0, MPI_COMM_WORLD);
#endif
}
```

**Comment by jinzx10** [comment] 2023-09-18 14:42
update:
In a ubuntu container with IntelLLVM 2022.1.0 compiler (intel-oneapi-compiler-dpcpp-cpp-and-cpp-classic/2022.1.0-3768]), the compiled code run normally; after upgrading to the latest version (intel-oneapi-compiler-dpcpp-cpp-and-cpp-classic/2023.2.1-16), the code reports the error in OP. There's a chance that this is a compiler issue.

**Comment by caic99** [comment] 2023-09-19 08:22
Hi @jinzx10 ,
After investigating carefully into disassembly generated, I think this issue happens on the erroneous vectorization on `auto const_C = force[i] / allmass[i]`. The compiler tries to employ SSE instructions on initializing `const_C` in "register allocation" of it. The SIMD instructions generated for `Vector3` overlaps on the second element of it (I guess). This makes the calculation result abnormally large on the y-component of the atom velocity. Using `gdb`, I observed that `const_C.y` is extra large, while `const_D` is correct.

I modified the codes as below mimicking the instantiation of `const_D`, and it works (even in `-fp-model=fast`):
```cpp
ModuleBase::Vector3<double> const_C;
const_C = force[i] / allmass[i];
```

This syntax will disable register allocation optimization for `const_C`, allocating memory for it; printing it out do the same thing.

I think this is a compiler issue: hard to detect and seldom seen. I can not tell whether codes from ABACUS is malformed. They all look good to me. 
@jinzx10 Would you figure out a minimum reproducible case using `Vector3` for Intel LLVM compiler? Thanks.

**Comment by jinzx10** [comment] 2023-09-19 09:28
> Hi @jinzx10 , After investigating carefully into disassembly generated, I think this issue happens on the erroneous vectorization on `auto const_C = force[i] / allmass[i]`. The compiler tries to employ SSE instructions on initializing `const_C` in "register allocation" of it. The SIMD instructions generated for `Vector3` overlaps on the second element of it (I guess). This makes the calculation result abnormally large on the y-component of the atom velocity. Using `gdb`, I observed that `const_C.y` is extra large, while `const_D` is correct.
> 
> I modified the codes as below mimicking the instantiation of `const_D`, and it works (even in `-fp-model=fast`):
> 
> ```c++
> ModuleBase::Vector3<double> const_C;
> const_C = force[i] / allmass[i];
> ```
> 
> This syntax will disable register allocation optimization for `const_C`, allocating memory for it; printing it out do the same thing.
> 
> I think this is a compiler issue: hard to detect and seldom seen. I can not tell whether codes from ABACUS is malformed. They all look good to me. @jinzx10 Would you figure out a minimum reproducible case using `Vector3` for Intel LLVM compiler? Thanks.

Thank you very much! That's been a great help. I'll try to figure out a minimum reproducible case...

**Comment by jinzx10** [comment] 2023-09-19 12:56
The following code is adapted from module_md/msst.cpp and constitutes a minimal example of the issue. 

The purpose of the code was to update 'vel' from 'force' and some other variables. A few intermediate results are printed out for debugging purpose. We found that the values of const_C & const_D have unexpected changes within the inner loop, thereby resulting in the wrong vel. 

We found that the issue exists when using

Intel(R) oneAPI DPC++/C++ Compiler 2023.2.0 (2023.2.0.20230721)

with -O2 or more optimization, but does not exist with -O1. We also found that this issue does not exists when we use an older version:

Intel(R) oneAPI DPC++/C++ Compiler 2022.0.0 (2022.0.0.20211123)

The tests were performed in 2 environments:
1. A ubuntu docker container with intel onapi compilers installed by apt
2. Windows 11 WSL2 with compilers installed by toolkit downloaded from intel website.

```cpp
#include <cstdio>
#include <iostream>
#include <cmath>

class Vector3 {
public:
    Vector3(double a = 0.0, double b = 0.0, double c = 0.0): x(a), y(b), z(c) {}
    Vector3(const Vector3& v): x(v.x), y(v.y), z(v.z) {}

    Vector3& operator+=(const Vector3& v) {
        x += v.x;
        y += v.y;
        z += v.z;
        return *this;
    }

    double& operator[](int index)
    {
        return (&x)[index];
    }

    void set(double u, double v, double w) {
        x = u;
        y = v;
        z = w;
    }

    double x;
    double y;
    double z;
};


int main() {
    double dt_half = 0.157;
    double fac = 3.14;
    int nat = 2;

    Vector3* vel = new Vector3[nat];
    Vector3* force = new Vector3[nat];
    for (int i = 0; i < nat; ++i) {
        vel[i].set(4.0 + i, 5.0 + 2*i, 6.0 + 3*i);
        force[i].set(1.0 + i, 2.0 + 2*i, 3.0 + 3*i);
    }

    for (int i = 0; i < nat; ++i) {
        Vector3 const_C = force[i];
        printf("const_C = % 18.12e   % 18.12e   % 18.12e\n", const_C[0], const_C[1], const_C[2]);

        Vector3 const_D(fac, fac, fac);
        printf("const_D = % 18.12e   % 18.12e   % 18.12e\n", const_D[0], const_D[1], const_D[2]);

        for (int k = 0; k < 3; ++k) {
            if (std::abs(dt_half * const_D[k]) > 1e-6) {
                printf("if: i = %i   k = %i   before: v = % 18.12e   c = % 18.12e   d = % 18.12e\n",
                         i, k, vel[i][k], const_C[k], const_D[k]);
                std::cout << const_C[k] << " " << const_D[k] << " " << vel[i][k] << std::endl; // comment out to see nan
                vel[i][k] = ( fac * (const_C[k] + const_D[k] * vel[i][k]) - const_C[k]) / const_D[k];
                printf("if:                 after : v = % 18.12e\n\n", vel[i][k]);
            } else {
                printf("else: i = %i   k = %i   before: v = % 18.12e   dt/2 = % 18.12e   c = % 18.12e   d = % 18.12e\n",
                        i, k, vel[i][k], dt_half, const_C[k], const_D[k]);
                vel[i][k]
                    += (const_C[k] + const_D[k] * vel[i][k]) * dt_half
                       + 0.5 * (const_D[k] * const_D[k] * vel[i][k] + const_C[k] * const_D[k]) * dt_half * dt_half;
                printf("else:                 after : v = % 18.12e\n\n", vel[i][k]);
            }
        }
    }

    delete[] vel;
    delete[] force;

    return 0;
}

```

When the code is compiled with g++, clang++ or older version of icpx, the output is 
```
const_C =  1.000000000000e+00    2.000000000000e+00    3.000000000000e+00
const_D =  3.140000000000e+00    3.140000000000e+00    3.140000000000e+00
if: i = 0   k = 0   before: v =  4.000000000000e+00   c =  1.000000000000e+00   d =  3.140000000000e+00
1 3.14 4
if:                 after : v =  1.324152866242e+01

if: i = 0   k = 1   before: v =  5.000000000000e+00   c =  2.000000000000e+00   d =  3.140000000000e+00
2 3.14 5
if:                 after : v =  1.706305732484e+01

if: i = 0   k = 2   before: v =  6.000000000000e+00   c =  3.000000000000e+00   d =  3.140000000000e+00
3 3.14 6
if:                 after : v =  2.088458598726e+01

const_C =  2.000000000000e+00    4.000000000000e+00    6.000000000000e+00
const_D =  3.140000000000e+00    3.140000000000e+00    3.140000000000e+00
if: i = 1   k = 0   before: v =  5.000000000000e+00   c =  2.000000000000e+00   d =  3.140000000000e+00
2 3.14 5
if:                 after : v =  1.706305732484e+01

if: i = 1   k = 1   before: v =  7.000000000000e+00   c =  4.000000000000e+00   d =  3.140000000000e+00
4 3.14 7
if:                 after : v =  2.470611464968e+01

if: i = 1   k = 2   before: v =  9.000000000000e+00   c =  6.000000000000e+00   d =  3.140000000000e+00
6 3.14 9
if:                 after : v =  3.234917197452e+01
```

When the issue is present, the outcome changes from run to run. For instance,
```
const_C =  1.000000000000e+00    2.000000000000e+00    3.000000000000e+00
const_D =  3.140000000000e+00    3.140000000000e+00    3.140000000000e+00
if: i = 0   k = 0   before: v =  4.000000000000e+00   c =  1.000000000000e+00   d =  3.140000000000e+00
1 3.14 4
if:                 after : v =  1.324152866242e+01

else: i = 0   k = 1   before: v =  5.000000000000e+00   dt/2 =  1.570000000000e-01   c =  2.567614915843e-312   d =  6.929202120609e-310
else:                 after : v =  5.000000000000e+00

else: i = 0   k = 2   before: v =  6.000000000000e+00   dt/2 =  1.570000000000e-01   c = -1.490606689495e+175   d =  6.929202193195e-310
else:                 after : v = -2.340252502508e+174

const_C =  2.000000000000e+00    4.000000000000e+00    6.000000000000e+00
const_D =  3.140000000000e+00    3.140000000000e+00    3.140000000000e+00
if: i = 1   k = 0   before: v =  5.000000000000e+00   c =  2.000000000000e+00   d =  3.140000000000e+00
2 3.14 5
if:                 after : v =  1.706305732484e+01

else: i = 1   k = 1   before: v =  7.000000000000e+00   dt/2 =  1.570000000000e-01   c =  2.567614915843e-312   d =  6.929202120609e-310
else:                 after : v =  7.000000000000e+00

else: i = 1   k = 2   before: v =  9.000000000000e+00   dt/2 =  1.570000000000e-01   c = -1.490606689495e+175   d =  6.929202193195e-310
else:                 after : v = -2.340252502508e+174
```

**Comment by caic99** [comment] 2023-09-22 08:26
Hi @jinzx10 ,
Here
```c++
    double& operator[](int index)
    {
        return (&x)[index];
    }
```
it's important to note that this approach relies on the assumption that the member variables are stored consecutively in memory. While this is true for most compilers, it's not guaranteed by the C++ standard. This article explains it pretty well:
[Accessing struct data members via pointer arithmetic](https://stackoverflow.com/questions/58428562/accessing-struct-data-members-via-pointer-arithmetic)
The compiler tries to take advantage of all the C++ rules, when analyzing what a pointer may point to. If a pointer is known to point to a distinct object such as a field of a structure, the compiler will assume that adding a value will not change the object that it points to.
There is an option to tell the compiler that the code may not follow the C++ aliasing rules very strictly: `-fno-strict-aliasing`
will allow the code to work.
@jinzx10 Maybe we should refactor `Vector3` to comply with C++ standard.

**Closed as completed** 2023-09-25 08:17 UTC
Labels: Bugs
