### ISSUE TITLE
Compilation of ABACUS v3.3.0 fails on DCU platform

### ISSUE THREAD

**Issue by flshbc** [deepmodeling/abacus-develop#2804] opened 2023-08-08 08:13 UTC
### Describe the bug

ABACUS (v3.3.0 and later) can not be successfully compiled on DCU platform according to [the previously established method](https://mcresearch.github.io/abacus-user-guide/abacus-dcu.html).

Compilation failure occurs between v3.2.5 and v3.3.0, but I could not locate the specific commit that leads to the problem.

v3.3.0: 
cmake confiure:
![3 2 5-1](https://github.com/deepmodeling/abacus-develop/assets/108002695/fdbd52b4-c765-458d-8fd9-0a308bfb7c3a)
![3 2 5-2](https://github.com/deepmodeling/abacus-develop/assets/108002695/0b7ac271-3577-4920-abe9-0e77381791c5)

make (failed):
![3 3 0-error](https://github.com/deepmodeling/abacus-develop/assets/108002695/8ad9f374-cf15-49b7-9bde-c198c61839de)
screen output around the error: [DCU-3.3.0-error.txt](https://github.com/deepmodeling/abacus-develop/files/12288831/DCU-3.3.0-error.txt)

### Expected behavior

An ideal compilation process would produce a plane-wave version of ABACUS. This goal can be achieved with ABACUS v3.2.5 and earlier version.

cmake configure:
![3 2 5-1](https://github.com/deepmodeling/abacus-develop/assets/108002695/04b081c9-5bad-48a3-b37a-afd7689d05c5)
![3 2 5-2](https://github.com/deepmodeling/abacus-develop/assets/108002695/7747385e-947e-4b06-8e08-ca37f3e0167b)

make:
![3 2 5-result](https://github.com/deepmodeling/abacus-develop/assets/108002695/75bdabd9-ed5b-450d-ab3b-c32dc3f9e7a7)

### To Reproduce

```
#environment
module purge
module load compiler/devtoolset/7.3.1
module load compiler/rocm/dtk-22.10 
module load compiler/cmake/3.17.2 
module load mpi/hpcx/2.6.0/gcc-7.3.1

#clone
git clone https://gitee.com/deepmodeling/abacus-develop -b v3.3.0
cd abacus-develop-3.3.0

#cmake configure
CC=clang CXX=clang++ cmake -B build -DUSE_OPENMP=OFF -DENABLE_LCAO=OFF \
-DFFTW3_DIR=/work/home/your_username/fftw-3.3.10/build/ \
-DLAPACK_DIR=/work/home/your_username/OpenBLAS-0.3.21/build/lib \
-DSCALAPACK_DIR=/work/home/your_username/scalapack-2.2.0/ \
-DUSE_ROCM=ON

#make
cd build
make
```

### Environment

OS: centos-build-7.6
compiler: clang/clang++ 14.0.0
dependencies: FFTW3/OpenBLAS/scaLAPACK/DCU Tool Kit
modules (take wuzhen node as an example): 
1. compiler/devtoolset/7.3.1
2. compiler/rocm/dtk-22.10 
3. compiler/cmake/3.17.2 
4. mpi/hpcx/2.6.0/gcc-7.3.1

### Additional Context

Currently, I guess resolving the potential conflicts in CMakelists.txt (or the codes) would be a straight-forward solution. In the future, there may be a simpler procedure to compile ABACUS on DCU platform.

**Comment by hongriTianqi** [comment] 2023-08-08 08:41
@denghuilu Would you please have a look of this issue?

**Comment by hongriTianqi** [comment] 2023-09-09 07:29
- [x] Verify the issue is not a duplicate.
- [x] Describe the bug.
- [x] Steps to reproduce.
- [x] Expected behavior.
- [x] Error message.
- [x] Environment details.
- [x] Additional context.
- [x] Assign a priority level (low, medium, high, urgent).
- [x] Assign the issue to a team member.
- [x] Label the issue with relevant tags.
- [x] Identify possible related issues.
- [x] Create a unit test or automated test to reproduce the bug (if applicable).
- [x] Fix the bug.
- [x] Test the fix.
- [x] Update documentation (if necessary).
- [x] Close the issue and inform the reporter (if applicable).

**Closed as completed** 2023-09-25 02:09 UTC
Labels: Bugs
