### ISSUE TITLE
Sometimes extremely slow in LCAO base code using intel-OneAPI with cmake compiling method

### ISSUE THREAD

**Issue by dyzheng** [deepmodeling/abacus-develop#1207] opened 2022-09-06 06:06 UTC
### Details

Sometimes "cmake --build build" with tiny updates and not delete old "build" directory would cause extremely slow in LCAO base test cases, such as tests/integrate/220_NO_KP_MD_NVE .
During my tests, I found that delete "build" directory and rebuild by cmake can solve this problem(in figure below, yellow is rebuild results, and orange is problematic results)
![image](https://user-images.githubusercontent.com/49852742/188558007-85376713-fdd0-4675-8885-015ec34e9b8b.png)

**Comment by caic99** [comment] 2022-09-06 06:08
Hi @dyzheng ,
Could you provide an example of "tiny updates"?

**Comment by dyzheng** [comment] 2022-09-06 06:19
> Hi @dyzheng , Could you provide an example of "tiny updates"?

To be honest, I can't repeat this problem on purpose. But I often find this problem when I reopen my working container in the morning of a workday, and commit some tiny updates then want to test code performance.
This issue's purpose is to record this situation and solutions.

**Comment by caic99** [comment] 2022-09-06 06:36
> 



> > Hi @dyzheng , Could you provide an example of "tiny updates"?
> 
> To be honest, I can't repeat this problem on purpose. But I often find this problem when I reopen my working container in the morning of a workday, and commit some tiny updates then want to test code performance. This issue's purpose is to record this situation and solutions.

Hi @dyzheng ,
I noticed that you are performing tests in a container, and I doubt this issue is related to other processes occupying CPU resources. For the next time this situation happens, would you check the utilization of other containers(if any) and system overhead.

**Comment by dyzheng** [comment] 2022-09-06 06:47
> > 
> 
> > > Hi @dyzheng , Could you provide an example of "tiny updates"?
> > 
> > 
> > To be honest, I can't repeat this problem on purpose. But I often find this problem when I reopen my working container in the morning of a workday, and commit some tiny updates then want to test code performance. This issue's purpose is to record this situation and solutions.
> 
> Hi @dyzheng , I noticed that you are performing tests in a container, and I doubt this issue is related to other processes occupying CPU resources. For the next time this situation happens, would you check the utilization of other containers(if any) and system overhead.

Thank for your remind, but I ensure this is not the reason for this problem. The node of the container is exclusive.

**Comment by caic99** [comment] 2022-09-06 06:49
> Thank for your remind, but I ensure this is not the reason for this problem. The node of the container is exclusive.

@dyzheng Have you checked system overhead?

**Comment by caic99** [comment] 2022-10-11 03:00
I'm not able to reproduce this bug, and it seems not to be so related to the code itself. 
Closing this issue; @dyzheng For the next time it happens, make a copy of your executable and let's dig out the truth.

**Closed as completed by caic99** 2022-10-11 03:00 UTC
