### ISSUE TITLE
use MPI in the function of Local_Orbital_Charge::cal_dk_k

### ISSUE THREAD

**Issue by Satinelamp** [deepmodeling/abacus-develop#2728] opened 2023-07-16 18:34 UTC
### Describe Current Status and Possible Solution

I use `MPI -n cores abacus` to test the parallel performance, but the time consumption of `Local_Orbital_Charge::cal_dk_k` is nearly the same as I use more cores.
![image](https://github.com/deepmodeling/abacus-develop/assets/62006565/999436ed-752f-41a3-9467-eacf3e8f96f7)

And the code of `Local_Orbital_Charge::cal_dk_k` only support using `openmp`. 
https://github.com/deepmodeling/abacus-develop/blob/4ad5f2019d981f62f2a8bb57a64ffbb502d94fdc/source/module_hamilt_lcao/hamilt_lcaodft/DM_k.cpp#L241

Maybe we should enhance this function to use MPI, too.

**Comment by hongriTianqi** [comment] 2023-08-03 08:40
@Satinelamp Thanks for your tests! This function actually has MPI function, which are included in the Grid_Technique. We are working to optimize its performance. Please expect newer versions of ABACUS. If no further problems on this function, I will close this issue.

**Comment by hongriTianqi** [comment] 2023-09-09 07:39
- [ ] Identify the specific code file or section with the code quality issue.
- [ ] Investigate the issue and determine the root cause.
- [ ] Research best practices and potential solutions for the identified issue.
- [ ] Refactor the code to improve code quality, following the suggested solution.
- [ ] Ensure the refactored code adheres to the project's coding standards.
- [ ] Test the refactored code to ensure it functions as expected.
- [ ] Update any relevant documentation, if necessary.
- [ ] Submit a pull request with the refactored code and a description of the changes made.

**Comment by WHUweiqingzhou** [comment] 2023-10-10 02:15
@Satinelamp
In our latest version v3.4.0, class `Local_Orbital_Charge` has been replaced by a new class `DensityMatrix` in the main procedure more or less, and the MPI transfer function `cal_dk_k` is replaced by a new function `transfer_DM2DtoGrid()`. The problem has been solved in this refactor. 
If you are interested in the new implement, you can also check the performance of `transfer_DM2DtoGrid()`.

**Comment by hongriTianqi** [comment] 2023-10-17 03:32
@Satinelamp Could you please test if this issue still exists? If it has been solved, we will close this issue. Thanks!

**Closed as completed** 2023-10-17 10:04 UTC
