### ISSUE TITLE
Failure of stress with DFTU && gamma_only 

### ISSUE THREAD

**Issue by dyzheng** [deepmodeling/abacus-develop#1899] opened 2023-02-16 04:37 UTC
### Describe the bug

I tried to set "cal_force  1" in tests/integrate/260_NO_15_PK_PU_AF and tests/integrate/360_NO_15_GO_PU_AF, it is okay.

I tried to set "cal_stress 1" in two cases above, it is correct in tests/integrate/260_NO_15_PK_PU_AF but the calculation is failure in tests/integrate/360_NO_15_GO_PU_AF:
```
 -------------------------------------------
 START CHARGE      : atomic
 DONE(2.80854    SEC) : INIT SCF
 ITER   TMAG      AMAG      ETOT(eV)       EDIFF(eV)      DRHO       TIME(s)    
 GV1    2.08e-04  2.94e+00  -7.322954e+03  0.000000e+00   9.901e-02  1.352e+00  
 GV2    -4.27e-04 3.09e+00  -7.291983e+03  3.097043e+01   1.138e-01  1.267e+00  
 GV3    1.28e-03  4.99e+00  -7.297545e+03  -5.561989e+00  7.932e-02  1.211e+00  
 !! CONVERGENCE HAS NOT BEEN ACHIEVED !!

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 0 PID 21198 RUNNING AT e5b216b907bd
=   KILLED BY SIGNAL: 11 (Segmentation fault)
===================================================================================
```

### Expected behavior

Setting "cal_force 1" and "cal_stress 1" in tests/integrate/360_NO_15_GO_PU_AF, the CI tests can pass either.

**Comment by dyzheng** [comment] 2023-03-24 11:39
@wenfei-li What status about this issue?

**Comment by wenfei-li** [comment] 2023-04-23 05:28
I only fixed for multi-k in this pr: https://github.com/deepmodeling/abacus-develop/pull/1868; the same can be done for gamma point calculation.
I will not be in charge of DFT+U functionality from now on.

**Comment by wenfei-li** [comment] 2023-08-07 08:36
There's a more recent issue about this bug, so I'll close this one.

**Comment by mohanchen** [comment] 2023-08-13 12:25
Which issue, link with this issue.

**Comment by hongriTianqi** [comment] 2023-09-09 07:08
- [ ] Verify the issue is not a duplicate.
- [x] Describe the bug.
- [ ] Steps to reproduce.
- [x] Expected behavior.
- [x] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by dyzheng** [comment] 2024-02-22 07:56
Please pay attention to https://github.com/deepmodeling/abacus-develop/issues/3588 , the new DFT+U method would solve this problem.

**Closed as completed** 2024-04-11 07:59 UTC
Labels: DFT+U
