### ISSUE TITLE
Warning of reading the pseudopotential file of Mg

### ISSUE THREAD

**Issue by Skyinner** [deepmodeling/abacus-develop#2194] opened 2023-04-05 09:12 UTC
### Details

I use the ABACUS to run scf of MgO systems. And I found that the output has a warning about reading a pseudopotential file:

```
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 Warning: number valence electrons > 2 for Mg: [Ne] 3s2 
 Please make sure the pseudopotential file is what you need
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
```

My pseudopotential file is: Mg_ONCV_PBE-1.0.upf from SG15_ONCV_v1.0_upf
My numerical orbital file is: Mg_gga_9au_100Ry_4s2p1d.orb from Orb_SG15_DZP_E100_Standard_v1.0

I feel unsafe about this warning. And I want to ask whether I should ignore this warning.

Following is the STRU file:
```
ATOMIC_SPECIES
Mg 24.305 Mg_ONCV_PBE-1.0.upf
O 15.999 O_ONCV_PBE-1.0.upf

NUMERICAL_ORBITAL
Mg_gga_9au_100Ry_4s2p1d.orb
O_gga_7au_100Ry_2s2p1d.orb

LATTICE_CONSTANT
1.8897259886

LATTICE_VECTORS
  10.000000000000000     0.000000000000000     0.000000000000000
   0.000000000000001    10.000000000000000     0.000000000000000
   0.000000000000000     0.000000000000000    10.000000000000000

ATOMIC_POSITIONS
Cartesian
Mg
0
1
   0.545797522548470     0.545754523320221     0.890599876125206  1  1  1
O
0
1
   1.454202477451581     1.454245476679781     2.109400123874785  1  1  1
```

Following is the INPUT file:

```
INPUT_PARAMETERS
suffix  MgO
ntype   2
pseudo_dir      /public1/home/sch2327/shipengjie/01-app/ABACUS/SG15_ONCV_v1.0_upf
orbital_dir     /public1/home/sch2327/shipengjie/01-app/ABACUS/Orb_SG15_DZP_E100_Standard_v1.0
scf_thr 1e-05
scf_nmax        100
ecutwfc 100
basis_type      lcao
nspin   1
gamma_only      1
calculation     scf
mixing_type     pulay
mixing_beta     0.3
mixing_ndim     8
mixing_gg0      1.5
smearing_method fd
smearing_sigma_temp     300
cal_force       1
cal_stress      1
```

[MgO.log](https://github.com/deepmodeling/abacus-develop/files/11157122/MgO.log)

**Comment by sunliang98** [comment] 2023-04-05 10:22
Since Mg contains two valence electrons, a pseudopotential containing two electrons is usually sufficient to handle it. Pseudopotentials containing more electrons (such as 10 electrons) can also produce correct results, but may be less efficient. If you're confident that the pseudopotential you're using is appropriate, you can safely ignore the warning.

This warning was intended to inform users about the information above, but it may cause confusion. Thank you for bringing this to our attention, and we will update it soon.

**Comment by sunliang98** [comment] 2023-04-10 02:59
Do you have other questions? Otherwise, we will close this issue. @Skyinner

**Closed as completed** 2023-04-11 10:36 UTC
