### ISSUE TITLE
Errors occurred when too many atoms calculated in a process

### ISSUE THREAD

**Issue by PeizeLin** [deepmodeling/abacus-develop#2044] opened 2023-03-10 03:53 UTC
### Describe the bug

\>3000 atoms. PBE, scf.

Perhaps some int variables are limited like #2002 .
Memory is available since a node with 3TB DRAM is used in the following two cases.

[C_17_k1_8-7_k.zip](https://github.com/deepmodeling/abacus-develop/files/10938277/C_17_k1.zip)
[Si_12_k1_1-56_k.zip](https://github.com/deepmodeling/abacus-develop/files/10938276/Si_12_k1_1-56_k.zip)

**Comment by hongriTianqi** [comment] 2023-09-09 07:13
- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by mohanchen** [comment] 2024-11-23 07:11
Since no actions are expected after so long time, I will close this issue.

**Closed as completed by mohanchen** 2024-11-23 07:11 UTC
Labels: Large Systems, Interfaces
