### ISSUE TITLE
Cannot continue in DFT+U AIMD

### ISSUE THREAD

**Issue by iduygnay** [deepmodeling/abacus-develop#2793] opened 2023-08-03 13:03 UTC
### Describe the bug

Please find attached the file of my case of AIMD for DFT+U.
[PBE+U.zip](https://github.com/deepmodeling/abacus-develop/files/12251077/PBE%2BU.zip)

**Comment by hongriTianqi** [comment] 2023-08-04 01:00
The force is extremely large, resulting in abortion:
```
><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><

    TOTAL-FORCE (eV/Angstrom)

 ><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><

     atom              x              y              z
       C1     -39819.46929938-15804667262351350.00000000         +0.31539789
       C2     -39819.46929938-15804667590404392.00000000         +0.49467453
       C3     -39819.46952113-15804667580970140.00000000         +0.70420589
       C4     -39819.46952113-15804665783600530.00000000         +1.16973748
       C5     -39819.46929938-15804667263461474.00000000         +0.72639162
       C6     -39819.46929938-15804667594115690.00000000         +0.39373074
       C7     -39819.46952113-15804667539599998.00000000         +0.46211464
       C8     -39819.46952113-15804665788307492.00000000         +0.30610172
       N1     -39850.79443870-15804667395202702.00000000         +0.31293779
       N2     -39850.79443870-15804667578069332.00000000         -0.19109495
       N3     -39850.79328956-15804667498519792.00000000         +0.41198578
       N4     -39850.79328956-15804666883017572.00000000         +0.26338474
       N5     -39850.79443870-15804667377719370.00000000         +0.42071224
       N6     -39850.79443870-15804667524529132.00000000         +0.11532212
       N7     -39850.79328956-15804667485271752.00000000         +0.90248277
       N8     -39850.79328956-15804666879098586.00000000         +0.91417923
       N9     -39851.37157181-15804667376213772.00000000         +0.50108564
      N10     -39851.37157181-15804667520493514.00000000         +0.47916800
      N11     -39851.37106767-15804667499363682.00000000         +0.08785874
      N12     -39851.37106767-15804666873650498.00000000         +0.38189402
      N13     -39851.37157181-15804667398874058.00000000         +0.66916626
      N14     -39851.37157181-15804667582067572.00000000         +0.92589706
      N15     -39851.37106767-15804667484182584.00000000         +0.74995438
      N16     -39851.37106767-15804666884777082.00000000         +0.73379371
       H1     -40093.24533624-15804667640551648.00000000         +0.56122637
       H2     -40093.24533624-15804667642672332.00000000         +0.56291045
       H3     -40093.24538371-15804667628187042.00000000         +0.54991428
       H4     -40093.24538371-15804667604383858.00000000         +0.54499341
       H5     -40093.24533624-15804667640517316.00000000         +0.55077522
       H6     -40093.24533624-15804667643613682.00000000         +0.54184629
       H7     -40093.24538371-15804667628132898.00000000         +0.34225989
       H8     -40093.24538371-15804667604254774.00000000         +0.41239477
       H9     -40021.20800679-15804667643094642.00000000         +0.57728020
      H10     -40021.20800679-15804667638731818.00000000         +1.28570396
      H11     -40021.20812935-15804667437606616.00000000         +0.55783513
      H12     -40021.20812935-15804666797025454.00000000         +0.32894758
      H13     -40021.20800679-15804667640524720.00000000         +0.65291531
      H14     -40021.20800679-15804667642700480.00000000         +0.63215367
      H15     -40021.20812935-15804667516440104.00000000         +0.76014613
      H16     -40021.20812935-15804667295597032.00000000         +1.22309273
      H17     -40043.52640251-15804667627047070.00000000         +0.43783620
      H18     -40043.52640251-15804667639111630.00000000         +0.38621083
      H19     -40043.52569451-15804667625776156.00000000         +0.39413154
      H20     -40043.52569451-15804667337053578.00000000         +0.49811392
      H21     -40043.52640251-15804667634005030.00000000         +0.57315338
      H22     -40043.52640251-15804667642777506.00000000         +0.66888478
      H23     -40043.52569451-15804667596653340.00000000         +0.56990155
      H24     -40043.52569451-15804667247679358.00000000         +0.53386864
      H25     -40043.59389185-15804667634193058.00000000         +0.43034242
      H26     -40043.59389185-15804667641756896.00000000         +0.40769756
      H27     -40043.59368012-15804667604053918.00000000         +0.48709710
      H28     -40043.59368012-15804667248324492.00000000         +0.68606857
      H29     -40043.59389185-15804667626880140.00000000         +0.90456544
      H30     -40043.59389185-15804667641234704.00000000         +0.54288807
      H31     -40043.59368012-15804667614323944.00000000         +0.56775712
      H32     -40043.59368012-15804667336842890.00000000         +0.54634469
      H33     -40022.34719167-15804667641220020.00000000         +0.53710693
      H34     -40022.34719167-15804667636240776.00000000         +0.53632552
      H35     -40022.34739798-15804667546981320.00000000         +0.67001346
      H36     -40022.34739798-15804667295639738.00000000         +1.23506586
      H37     -40022.34719167-15804667642796706.00000000         +0.52610232
      H38     -40022.34719167-15804667641116492.00000000         +0.38292043
      H39     -40022.34739798-15804667426654186.00000000         +0.54631322
      H40     -40022.34739798-15804666797004858.00000000         +0.41201481
      Pb1    +296226.11094749+34253899382377140.00000000        +25.84049406
      Pb2    +296226.88471742-15674809228727150.00000000         +0.43939795
      Pb3    +296225.43373871-14363821999109650.00000000        -14.98916814
      Pb4    +296226.20750741+799393686232907392.00000000       -249.50174082
      Pb5    +296226.11094735+31735276540299124.00000000        +73.83823840
      Pb6    +296226.88471737-15798060114090374.00000000         +1.90023937
      Pb7    +296225.43373855-15720202171197786.00000000        -18.09079624
      Pb8    +296226.20750735+586969251593489280.00000000       +124.40007421
       I1     +10712.30836462-15804159755134666.00000000         +6.06629058
       I2     +10712.41359496-15804622686994360.00000000         +2.09220174
       I3     +10712.03913459-15804664387404150.00000000         +8.06592527
       I4     +10712.14436447-15803886147056556.00000000         -0.98164335
       I5     +10712.30836462-15804160948791350.00000000         -4.22649344
       I6     +10712.41359496-15804622854641084.00000000         -4.84990502
       I7     +10712.03913459-15804667007607220.00000000        -16.30702868
       I8     +10712.14436447-15803891343471954.00000000         -6.71932465
       I9     +41093.39111284-15803663085116968.00000000        +22.19092864
      I10     +41093.55593465-15804663737661254.00000000         -6.61274667
      I11     +41093.41897029-15804655660561010.00000000         +0.69043379
      I12     +41093.58379215-15803460003244822.00000000        -87.55893122
      I13     +41093.39111278-15804263010483302.00000000       +128.94249370
      I14     +41093.55593464-15804664651363502.00000000         +0.36901696
      I15     +41093.41897022-15804665014116810.00000000         +0.89832948
      I16     +41093.58379214-15803693683046394.00000000        -40.08228974
      I17     -28286.31612720-15801388305092886.00000000         -1.71266455
      I18     -28286.31612717-15804285337828770.00000000         -3.39690849
      I19     -28286.31965951-15804634964922488.00000000         +0.74200139
      I20     -28286.31965948-15802661282974094.00000000         +4.58984185
      I21     -28286.31612720-15802795675975810.00000000         +1.85233328
      I22     -28286.31612717-15804497024952180.00000000         -0.08950835
      I23     -28286.31965952-15804639001983518.00000000         +1.62436283
      I24     -28286.31965948-15803200052258410.00000000        +14.76034405


 ------------------------------------------------------------------------------------------------
 Energy (Ry)         Potential (Ry)      Kinetic (Ry)        Temperature (K)     
 -6233.7487          -6234.0194          0.27076272          300                 
 ------------------------------------------------------------------------------------------------



 -------------------------------------------
 STEP OF MOLECULAR DYNAMICS : 1
 -------------------------------------------
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
                         NOTICE                           
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

 the movement of atom is larger than the length of cell.
 CHECK IN FILE : OUT.ABACUS/warning.log

 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
                         NOTICE                           
 !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
 Check in file : OUT.ABACUS/warning.log
```

**Comment by hongriTianqi** [comment] 2023-08-04 01:02
Molecular dynamics was run with U:
```
INPUT_PARAMETERS

calculation     md
ecutwfc         50.000000
scf_thr         1.000000e-6
scf_nmax        100

basis_type      lcao
dft_functional  pbe
gamma_only      1
#kspacing        0.1

mixing_type     pulay
mixing_beta     0.150000
mixing_gg0      1.5
smearing_method gauss
smearing_sigma  0.003

md_type         nvt
md_nstep        10000
md_dumpfreq     20
md_tfirst       300
md_tlast        300
md_dt           1
md_pfirst       1
#md_restart      1
chg_extrap      second-order

ks_solver genelpa
dft_plus_u    True
orbital_corr  -1 -1 -1 1 2
hubbard_u     0 0 0 1.9 3.7



```

**Comment by hongriTianqi** [comment] 2023-08-04 01:07
Info in the `warning.log` file
```
 it=1 ia=1
d=-0.00659166095553076 -498902653565.445 0.250229187187158
 Ions_Move_Basic::move_ions  warning : the movement of atom is larger than the length of cell.
```

**Comment by iduygnay** [comment] 2023-08-06 13:21
tho there must be something wrong with DFT+U AIMD since DFT+U AIMD can work well. 
please find attached the file of PBE AIMD.
[PBE.zip](https://github.com/deepmodeling/abacus-develop/files/12269684/PBE.zip)

**Comment by wenfei-li** [comment] 2023-08-07 03:12
might have something to do with this issue: https://github.com/deepmodeling/abacus-develop/issues/1899
gamma force needs to be fixed, and I have described how in that issue
for a quick solution you might just turn off gamma_only and run multi-k calculation with gamma point as the only k point

**Comment by iduygnay** [comment] 2023-08-07 06:15
another thing is, I want to add U at the type 4 and type 5 atoms, what's wrong with my INPUT?
![image](https://github.com/deepmodeling/abacus-develop/assets/109792836/ce1f56e7-8968-4c7e-b890-597ecdbfbfb8)

![image](https://github.com/deepmodeling/abacus-develop/assets/109792836/ab0072d4-cc0c-4ae9-a974-4c90b2bcbff5)

**Comment by wenfei-li** [comment] 2023-08-07 08:19
I suppose there is nothing wrong. It is just that the index starts from 0 ...

> another thing is, I want to add U at the type 4 and type 5 atoms, what's wrong with my INPUT? ![image](https://user-images.githubusercontent.com/109792836/258715003-ce1f56e7-8968-4c7e-b890-597ecdbfbfb8.png)
> 
> ![image](https://user-images.githubusercontent.com/109792836/258714922-ab0072d4-cc0c-4ae9-a974-4c90b2bcbff5.png)

**Comment by wenfei-li** [comment] 2023-08-07 08:20
btw does multi-k help? I'd be interested to know.

**Comment by iduygnay** [comment] 2023-08-07 08:21
yes, it works now! thank you so much! Do I need to close this issue?

**Comment by wenfei-li** [comment] 2023-08-07 08:35
> yes, it works now! thank you so much! Do I need to close this issue?

Good to know! And I feel it would be better to leave this open and close the older one about gamma force.

**Comment by hongriTianqi** [comment] 2023-09-09 07:29
- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Closed as completed** 2023-09-12 08:22 UTC
Labels: Bugs, DFT+U
