### ISSUE TITLE
The judgement of relax converge is unreasonable 

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#2627] opened 2023-06-13 08:21 UTC
### Describe the bug

In my test, I have run a relax calculation. The convergence of SCF is not achieved, but calculated force and stress meet relax convergence criteria, and ABACUS think the relax convergence is achieved. This is unreasonable, because the value of force and stress are unavailable. 

https://launching.mlops.dp.tech/?request=GET%3A%2Fapplications%2Fabacustest%2Fjobs%2Fjob-abacustest-develop-e3a6a2

[example.zip](https://github.com/deepmodeling/abacus-develop/files/11732401/example.zip)

**Comment by kirk0830** [comment] 2023-06-16 08:12
Dear Xingliang
Thanks. Commonly the threshold or criteria for judging whether a structure has been optimized may depend on several aspects, and the resulting structure is not always unreasonable if SCF is failed to converge while the force and stress have been decreased below their corresponding thresholds.
For example, in Quantum ESPRESSO, there is a keyword `scf_must_converge` [(pw.x: input description)](https://www.quantum-espresso.org/Doc/INPUT_PW.html#idm809) controlling whether unless the convergence of SCF has been reached will the structure relaxation be performed further, while in practice, this keyword is always set to false. Empirically the reason is, although SCF cannot get converged at present relaxation step or first several, even tens of relaxation steps, it will finally reach its convergence threshold during relaxation. But to achieve this, the wavefunction and charge extrapolation method must be efficient enough.
In CP2K, what is often the case is that the convergence of SCF will not determine whether geometry optimization can be performed. Every time when SCF fails to converge in maximal number of steps (user defined), at least one warning will pop up and, CP2K actually uses not one or two, but at least four convergence thresholds to judge whether one geometry optimization (cell optimization case included) is converged. They are: max force, rms of force, max displacement and rms displacement. [(CP2K_INPUT / MOTION / GEO_OPT)](https://manual.cp2k.org/cp2k-2023_1-branch/CP2K_INPUT/MOTION/GEO_OPT.html) For cell optimization there is another one: cell pressure [(PRESSURE_TOLERANCE).](https://manual.cp2k.org/cp2k-2023_1-branch/CP2K_INPUT/MOTION/CELL_OPT.html#PRESSURE_TOLERANCE) So even if cannot get good enough wavefunction, if the force and stress evaluation are consistent over relaxation steps, the result is roughly reliable.
Therefore, it is worth noting the quality and reliability of wavefunction and derived evaluated force and stress, but there will be more aspects that should be considered in ABACUS.
Hope that helps,
Yike

**Comment by pxlxingliang** [comment] 2023-06-16 08:52
Hi @kirk0830 
It is reasonable that do next relax step even SCF is not convergence. But if the unreliable force and stress satisfy the criteria of relax, should ABACUS stop the calculation and tell user that the relax is converged? 
Do you know how QE or VASP deal with such situation?

**Comment by kirk0830** [comment] 2023-06-16 10:02
I tried to look up all jobs run by QE and CP2K, but I did not find a single one similar case. I also consulted with experienced VASP users but still got little information.
The most common case is the not converged wavefunction will always spoil the convergence of geometry optimization, it means relaxation convergence is more difficult to reach compared with SCF.
I also tried to restart a `vc-relax` task on a fully optimized cell with randomly initialized wavefunction, but the force and stress are ill-evaluated at the first relax step which triggers further re-optimization, while during later relaxation, SCF reached its convergence threshold.
My suggestion may be popping up warning instead of quitting immediately, because for first-principle calculations, without wavefunction stability check, getting an appropriate wavefunction is a much more difficult task than simply geometry optimization. Even if SCF gets converged, it is still possible for the obtained wavefunction does not correspond to the ground state.

**Comment by pxlxingliang** [comment] 2023-06-16 10:16
I see, it seems appropriate to throw a warning for this small probability case.

**Comment by hongriTianqi** [comment] 2023-09-09 07:20
- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by hongriTianqi** [comment] 2023-09-14 07:21
@pxlxingliang This issue has been solved. A warning will be given on screen and in the log file:
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Relaxation is converged, but the SCF is unconverged! The results are unreliable.
It is suggested to increase the maximum SCF step and/or perform the relaxation again.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

**Closed as completed by hongriTianqi** 2023-09-14 07:21 UTC
Labels: Bugs
