### ISSUE TITLE
not converged with adding U

### ISSUE THREAD

**Issue by xdzhu** [deepmodeling/abacus-develop#2639] opened 2023-06-15 03:44 UTC
### Describe the bug

One can perform the scf calculation converged without adding hubbard U.
However, when the hubbard U is considered, the scf calculation is barely to converge.

Please test this sample and pave the way to convergence with hubbard U.

INPUT files are attached below [To Reproduce].

OUTPUT here:
![image](https://github.com/deepmodeling/abacus-develop/assets/55775434/c9f58237-a99c-4874-bc0c-75edcd599c10)

the FULL text:
[scf.txt](https://github.com/deepmodeling/abacus-develop/files/11752503/scf.txt)

### To Reproduce

[issue-addU-not-converged.zip](https://github.com/deepmodeling/abacus-develop/files/11752500/issue-addU-not-converged.zip)

**Comment by mohanchen** [comment] 2023-06-19 01:19
@wenfei-li answer the question (of course you can choose ignore)

**Comment by Satinelamp** [comment] 2023-06-23 02:58
In VASP, if we meet divergence, I would adjust `AMIX`, and `BMIX` for material that contains transition metals, maybe ABACUS could provide similar options?
Here is a set of methods to improve convergence in VASP:
http://bbs.keinsci.com/thread-13065-1-5.html

**Comment by wenfei-li** [comment] 2023-07-06 05:22
The convergence of +U calculation has always been a problem, and I do not have a good solution for it. You might try tuning some mixing parameters, sometimes it helps.

**Comment by wenfei-li** [comment] 2023-08-07 03:10
we have a similar problem, will close this one

**Comment by mohanchen** [comment] 2023-08-13 12:28
When someone fixes that one (which one? Link?) , one hould test this failure case and make sure this one also passes tests. After those tests, the issue can be closed.

**Comment by hongriTianqi** [comment] 2023-09-09 07:22
- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by dyzheng** [comment] 2024-02-22 07:53
Please pay attention to #3588 , the new DFT+U method would improve the convergence of SCF calculation.

**Comment by dyzheng** [comment] 2024-03-28 07:31
Can you try the latest v3.6.0?

**Closed as completed** 2024-04-11 08:05 UTC
Labels: DFT+U
