### ISSUE TITLE
How to draw the picture of wave functions?

### ISSUE THREAD

**Issue by Satinelamp** [deepmodeling/abacus-develop#2212] opened 2023-04-08 08:17 UTC
### Details

I am following the guide on the [official document](https://abacus.deepmodeling.com/en/latest/advanced/elec_properties/wfc.html) to extract the wave functions, but I don't know how to draw the picture of the wave function after I get the wave functions coefficients by setting `out_wfc_lcao=1`

**Comment by lyb9812** [comment] 2023-05-07 08:04
The content of output file for out_wfc_lcao=1 are coefficients of wave functions.  To print wave functions in real space , you need to set out_wfc_r=1 and calculation = ienvelope.

**Comment by hongriTianqi** [comment] 2023-09-09 07:42
- [ ] Understand the problem or question described by the user.
- [ ] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [ ] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Comment by mohanchen** [comment] 2024-10-17 12:40
ABACUS 输出部分的电荷密度和波函数及可视化教程 · GitBook  https://mcresearch.github.io/abacus-user-guide/abacus-chg.html

**Closed as completed** 2024-10-17 12:40 UTC
Labels: Input&Output
