### ISSUE TITLE
totally inverse K-path in ABACUS with the SAME INPUT from VASP

### ISSUE THREAD

**Issue by xdzhu** [deepmodeling/abacus-develop#2638] opened 2023-06-15 03:32 UTC
### Describe the bug

In this 2D material sample, the K-path is Gamma-K-K2-Gamma, while K and K2 are inequivalent valleys in the Brillouin zone.

It shows that the way that ABACUS treat the inequivalent K/K2 valley are **exactly inverse** comparing to the VASP result with the totally **SAME** klines. 

K_POINTS
4
Line
0.0000000000   0.0000000000   0.0000000000    60   # GAMMA          
0.3333333333   0.6666666667   0.0000000000    60   # K                  
-0.3333333333  0.3333333333   0.0000000000    60   # K2              
0.0000000000   0.0000000000   0.0000000000    1    # GAMMA 

Please figure out the reason and point out how to derive the same result.

![image](https://github.com/deepmodeling/abacus-develop/assets/55775434/871af192-ea21-4ee7-aaf2-d6b4c87c16b1)

### Expected behavior

SAME band structure with the SAME K-path.

### To Reproduce

Do scf and band calculation with spin-orbit coupling.

[issue-inverse-klines.zip](https://github.com/deepmodeling/abacus-develop/files/11752429/issue-inverse-klines.zip)

### Environment

ABACUS 3.2.4

**Comment by Satinelamp** [comment] 2023-06-23 03:37
Have you tested this issues for other materials?

**Comment by hongriTianqi** [comment] 2023-09-09 07:22
- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by hongriTianqi** [comment] 2023-10-25 08:00
need to revise lcao_in_pw

**Closed as completed** 2023-12-03 15:28 UTC
Labels: Bugs
