### ISSUE TITLE
Wrong & different total energy for Cu single crystal by using ABACUS&Dojo Pseudopotential compared with PWscf

### ISSUE THREAD

**Issue by wszhang** [deepmodeling/abacus-develop#2738] opened 2023-07-20 07:24 UTC
### Describe the bug

RT
We obtained wrong total energy for Cu single crystal by using ABACUS & Dojo FR/SR Pseudopotential. The results are compared with that calculated by PWscf, which is shown in the following Fig:
![image](https://github.com/deepmodeling/abacus-develop/assets/10769183/6ebee9a0-439a-4145-972c-1dda255b3a15)

### To Reproduce

Please use the following Code and Pseudopotential, you need to change the Shell-Environment and CMD variable in *.sh.

[code_and_pp.zip](https://github.com/deepmodeling/abacus-develop/files/12103170/code_and_pp.zip)

### Environment

Currently Loaded Modulefiles:
  1) intel/2019.update5                            3) mkl/2019.update5
  2) hpcx/2.9.0/hpcx-intel-2019.update5            4) QuantumESPRESSO/6.5/hpcx-intel-2019.update5

or 

Currently Loaded Modulefiles:
  1) gcc/9.2.0                         3) intel/2019.update5                5) mkl/2019.update5                  7) cmake/3.19.0
  2) elpa/2021.11.002/intelmpi2019     4) intelmpi/2019.update5             6) abacus/3.3.0/intel-2019.update5

**Comment by wszhang** [comment] 2023-07-20 07:33
[results.log](https://github.com/deepmodeling/abacus-develop/files/12103247/results.log)

Above contains some results, I tested 0.0/0.5 for magnetism and 1/2 for nspin and CG/DAV for ks_solver.

By using the SG15 PP instead of the Dojo PP, we can obtain the correct results:

![image](https://github.com/deepmodeling/abacus-develop/assets/10769183/2ad2d452-1000-47ab-9f4b-6aa6a9a005ff)

**Comment by dyzheng** [comment] 2023-07-20 07:58
I will test this issue.

**Comment by wszhang** [comment] 2023-07-20 09:26
If using "pseudo_rcut 10" and "pseudo_mesh 1" in INPUT, we can get allmost the same results by ABACUS and PWscf

![image](https://github.com/deepmodeling/abacus-develop/assets/10769183/1b958e34-7ce1-4952-b859-7d4569d1cdaa)

**Comment by wszhang** [comment] 2023-07-21 01:42
To achieve the same results as PWscf, only "pseudo_rcut 10" is required.

**Comment by wszhang** [comment] 2023-07-25 05:36
If using "pseudo_rcut 10" and LCAO to calculate Volume-Energy for Cr single crystal, one will find the numerical instability.

results:
![image](https://github.com/deepmodeling/abacus-develop/assets/10769183/3d32e187-04e9-47e7-b721-d4888e80806a)


code:
[Cr_Dojo_PPrcut10.zip](https://github.com/deepmodeling/abacus-develop/files/12157453/Cr_Dojo_PPrcut10.zip)

log：
[run1.log](https://github.com/deepmodeling/abacus-develop/files/12157476/run1.log)

**Comment by hongriTianqi** [comment] 2023-08-03 07:10
@wszhang One further comment: after checking the `run1.log` file, I find that the results for orbitals with rcut = 10 a.u. is normal, only that for rcut = 9 a.u. have problems. Do you have access to orbitals with larger rcut to check the issue again?
The log files show that results for rcut = 10 a.u. are:
```
./OUT.Cr.LCAO.DojoFR.V0/running_scf.log: !FINAL_ETOT_IS -4842.806414133842 eV
./OUT.Cr.LCAO.DojoFR.V1/running_scf.log: !FINAL_ETOT_IS -4842.844977169378 eV
./OUT.Cr.LCAO.DojoFR.V2/running_scf.log: !FINAL_ETOT_IS -4842.870428051072 eV
./OUT.Cr.LCAO.DojoFR.V3/running_scf.log: !FINAL_ETOT_IS -4842.885135378884 eV
./OUT.Cr.LCAO.DojoFR.V4/running_scf.log: !FINAL_ETOT_IS -4842.756609354389 eV
./OUT.Cr.LCAO.DojoFR.V5/running_scf.log: !FINAL_ETOT_IS -4842.718779057626 eV
./OUT.Cr.LCAO.DojoFR.V6/running_scf.log: !FINAL_ETOT_IS -4842.670022183407 eV
``` 
and that for rcut = 9 a.u. are:
```
./OUT.Cr.LCAO.DojoFR.V0/running_scf.log: !FINAL_ETOT_IS -4842.823774847230 eV
./OUT.Cr.LCAO.DojoFR.V1/running_scf.log: !FINAL_ETOT_IS -4842.862849905267 eV
./OUT.Cr.LCAO.DojoFR.V2/running_scf.log: !FINAL_ETOT_IS -4842.888588016534 eV
./OUT.Cr.LCAO.DojoFR.V3/running_scf.log: !FINAL_ETOT_IS -4842.903428275203 eV
./OUT.Cr.LCAO.DojoFR.V4/running_scf.log: !FINAL_ETOT_IS -4842.908645206262 eV
./OUT.Cr.LCAO.DojoFR.V5/running_scf.log: !FINAL_ETOT_IS -4842.742376487495 eV
./OUT.Cr.LCAO.DojoFR.V6/running_scf.log: !FINAL_ETOT_IS -4842.895249254954 eV
```

**Comment by jinzx10** [comment] 2023-08-08 07:49
This could be another case where lcao_ecut plays an important role. The figure below compares two orbital basis (9 & 10 au) and two lcao_ecut. With lcao_ecut = 400, the results from two basis sets basically agree.

However, the figure still looks strange at the largest bond length. There could be other factors that contribute to the numerical instability.

![issue_2738](https://github.com/deepmodeling/abacus-develop/assets/26805483/63e0bdd5-488a-43ac-9241-0ff03ddb3a66)

**Comment by wszhang** [comment] 2023-08-28 20:19
> @wszhang One further comment: after checking the `run1.log` file, I find that the results for orbitals with rcut = 10 a.u. is normal, only that for rcut = 9 a.u. have problems. Do you have access to orbitals with larger rcut to check the issue again? The log files show that results for rcut = 10 a.u. are:
> 
> ```
> ./OUT.Cr.LCAO.DojoFR.V0/running_scf.log: !FINAL_ETOT_IS -4842.806414133842 eV
> ./OUT.Cr.LCAO.DojoFR.V1/running_scf.log: !FINAL_ETOT_IS -4842.844977169378 eV
> ./OUT.Cr.LCAO.DojoFR.V2/running_scf.log: !FINAL_ETOT_IS -4842.870428051072 eV
> ./OUT.Cr.LCAO.DojoFR.V3/running_scf.log: !FINAL_ETOT_IS -4842.885135378884 eV
> ./OUT.Cr.LCAO.DojoFR.V4/running_scf.log: !FINAL_ETOT_IS -4842.756609354389 eV
> ./OUT.Cr.LCAO.DojoFR.V5/running_scf.log: !FINAL_ETOT_IS -4842.718779057626 eV
> ./OUT.Cr.LCAO.DojoFR.V6/running_scf.log: !FINAL_ETOT_IS -4842.670022183407 eV
> ```
> 
> and that for rcut = 9 a.u. are:
> 
> ```
> ./OUT.Cr.LCAO.DojoFR.V0/running_scf.log: !FINAL_ETOT_IS -4842.823774847230 eV
> ./OUT.Cr.LCAO.DojoFR.V1/running_scf.log: !FINAL_ETOT_IS -4842.862849905267 eV
> ./OUT.Cr.LCAO.DojoFR.V2/running_scf.log: !FINAL_ETOT_IS -4842.888588016534 eV
> ./OUT.Cr.LCAO.DojoFR.V3/running_scf.log: !FINAL_ETOT_IS -4842.903428275203 eV
> ./OUT.Cr.LCAO.DojoFR.V4/running_scf.log: !FINAL_ETOT_IS -4842.908645206262 eV
> ./OUT.Cr.LCAO.DojoFR.V5/running_scf.log: !FINAL_ETOT_IS -4842.742376487495 eV
> ./OUT.Cr.LCAO.DojoFR.V6/running_scf.log: !FINAL_ETOT_IS -4842.895249254954 eV
> ```

As jinzx10 commented above, the curve of results for orbitals with rcut = 10 a.u. & 100 Ry looks strange too.

**Comment by hongriTianqi** [comment] 2023-09-09 07:27
- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by jinzx10** [comment] 2024-01-08 08:10
Hi @wszhang , with the latest ABACUS on the develop branch, the V-E curve for Cr actually looks pretty good (see below)! Could you confirm that?

As shown in previous posts, the original numerical instability is not likely to be the consequence of errorneous two-center integral - at least this is not the only factor. As far as I know, there are not many changes since August 2023 that can affect the results. This can be seen from the figure below: for the most bond length, results from the latest & old ABACUS (lcao_ecut=400) do not differ too much; only the last data points differ dramatically.

Another possibility is the SCF convergence. Spin-polarized systems may converge to some wrong state with either inappropriate initial condition or terrible algorithm. Considering recent work on charge mixing by @WHUweiqingzhou , my conjecture is that previous SCF calculations, while claimed to have reach charge-density self-consistency, actually failed to find the right state; and this problem is systematically solved by @WHUweiqingzhou 's recent work on spin-polarized charge mixing.

@dyzheng @WHUweiqingzhou  Do you have any comments? Are there any other factors to cause this issue?

![image](https://github.com/deepmodeling/abacus-develop/assets/26805483/159ff97e-ba90-436d-adda-335b5d87d531)

**Comment by jinzx10** [comment] 2024-01-19 07:52
The above figure shows that the inconsistency of latest and previous version merely occurs to some isolated data points. For the abnormal data point in the above figure, I found that the problem existed until commit https://github.com/deepmodeling/abacus-develop/commit/9af48f8a3c1840398c2a88eca211d3b96fcc1ebe , but fixed in commit https://github.com/deepmodeling/abacus-develop/commit/fd76546b96bb49165437e9d500e8cae92c685bfc (PR https://github.com/deepmodeling/abacus-develop/pull/3226).

This suggests that some abnormal E-V curves might result from convergence to the wrong state, and @WHUweiqingzhou 's new mixing method significantly improves the ability to reach the right magnetic state.

**Closed as completed by jinzx10** 2024-01-19 07:52 UTC
Labels: Bugs
