### ISSUE TITLE
Different converged energy for H_2 molecule on Debian and CentOS

### ISSUE THREAD

**Issue by kluophysics** [deepmodeling/abacus-develop#4291] opened 2024-06-02 09:59 UTC
### Describe the bug

When running ABACUS on two platforms, I get two differen converged SCF energy for H_2 molecule. On two computers,
both  are compiled with 
``` 
cmake ../ -DUSE_ELPA=OFF -DCMAKE_CXX_COMPILER=icpx -DMPI_CXX_COMPILER=mpiicpc
``` 
and a single
cpu mpirun is used.
One is my local desktop with Debian 12 and the other one is a node with CentOS 7.6.

The INPUT file is
```
INPUT_PARAMETERS
pseudo_dir              ./
orbital_dir             ./
#nbands		10

calculation	scf

ecutwfc		50
scf_thr		1.0e-6
scf_nmax	100

smearing_method	gaussian
smearing_sigma	0.0002

#mixing_type	broyden
#mixing_beta	0.4

basis_type	lcao
gamma_only	0


out_freq_elec 1

printe       1
```

and the STRU file is
```

ATOMIC_SPECIES
H	1.008	H_ONCV_PBE-1.0.upf

NUMERICAL_ORBITAL
H_gga_8au_60Ry_2s1p.orb

LATTICE_CONSTANT
1.889725989 #1.889725989

LATTICE_VECTORS
20 0 0
0 20 0
0 0 20

ATOMIC_POSITIONS
Cartesian #(Unit is LATTICE_CONSTANT)
H
0.0
2
 0.0  0.0  0.0
 0.0  0.0  0.741
```
and Gamma point is used for KPT file
```
K_POINTS
0
Gamma
1 1 1 0 0 0
```

CentOS7.6:
```
...
DONE(7.43438    SEC) : INIT SCF
 ITER   ETOT(eV)       EDIFF(eV)      DRHO       TIME(s)    
 GV1    -3.029806e+01  0.000000e+00   1.021e+00  8.481e+00  
 GV2    -3.133219e+01  -1.034129e+00  2.220e-01  8.543e+00  
 GV3    -3.136159e+01  -2.940129e-02  6.259e-02  8.856e+00  
 GV4    -3.135289e+01  8.708804e-03   2.349e-02  8.998e+00  
 GV5    -3.135455e+01  -1.663262e-03  1.657e-02  9.040e+00  
 GV6    -3.135442e+01  1.262523e-04   1.152e-02  9.215e+00  
 GV7    -3.135411e+01  3.139192e-04   8.127e-03  9.398e+00  
 GV8    -3.135413e+01  -2.078493e-05  6.477e-03  9.356e+00  
 GV9    -3.135401e+01  1.145681e-04   4.678e-03  9.506e+00  
 GV10   -3.135396e+01  5.492063e-05   2.863e-03  9.627e+00  
 GV11   -3.135392e+01  3.506917e-05   1.469e-03  9.518e+00  
 GV12   -3.135390e+01  2.031156e-05   7.971e-04  9.548e+00  
 GV13   -3.135390e+01  5.113840e-06   5.063e-04  9.616e+00  
 GV14   -3.135390e+01  3.599309e-06   3.317e-04  9.527e+00  
 GV15   -3.135389e+01  5.070964e-06   1.636e-04  9.377e+00  
 GV16   -3.135389e+01  2.419819e-06   8.708e-05  9.435e+00  
 GV17   -3.135389e+01  5.825932e-07   5.812e-05  9.379e+00  
 GV18   -3.135389e+01  1.384851e-06   2.302e-05  9.436e+00  
 GV19   -3.135389e+01  5.878954e-07   7.430e-06  9.475e+00  
 GV20   -3.135389e+01  -1.424060e-08  4.034e-06  9.399e+00  
 GV21   -3.135389e+01  -5.191270e-08  2.202e-06  9.414e+00  
 GV22   -3.135389e+01  1.118008e-09   1.113e-06  9.442e+00  
 GV23   -3.135389e+01  1.724186e-08   2.646e-07  7.827e+00  
...
```

But on Debian, it is
```
...
 DONE(2.78004    SEC) : INIT SCF
 ITER   ETOT(eV)       EDIFF(eV)      DRHO       TIME(s)    
 GV1    -3.159126e+01  0.000000e+00   4.149e-01  3.764e+00  
 GV2    -3.166994e+01  -7.867466e-02  8.710e-02  3.790e+00  
 GV3    -3.167273e+01  -2.793260e-03  4.550e-02  3.777e+00  
 GV4    -3.167416e+01  -1.426838e-03  2.283e-02  3.815e+00  
 GV5    -3.167487e+01  -7.129307e-04  1.665e-02  3.749e+00  
 GV6    -3.167541e+01  -5.439987e-04  1.282e-02  3.751e+00  
 GV7    -3.167546e+01  -4.781610e-05  9.016e-03  3.772e+00  
 GV8    -3.167544e+01  1.882324e-05   6.283e-03  3.759e+00  
 GV9    -3.167544e+01  1.982604e-06   4.178e-03  3.745e+00  
 GV10   -3.167545e+01  -9.253647e-06  2.459e-03  3.760e+00  
 GV11   -3.167546e+01  -9.004416e-06  1.443e-03  3.783e+00  
 GV12   -3.167546e+01  -3.067559e-06  7.842e-04  3.753e+00  
 GV13   -3.167547e+01  -1.835209e-06  5.438e-04  3.790e+00  
 GV14   -3.167547e+01  -1.314409e-06  3.496e-04  3.752e+00  
 GV15   -3.167547e+01  -3.441134e-07  1.757e-04  3.780e+00  
 GV16   -3.167547e+01  -1.778557e-07  1.103e-04  3.781e+00  
 GV17   -3.167547e+01  -3.861338e-07  5.513e-05  3.818e+00  
 GV18   -3.167547e+01  -2.834358e-08  3.090e-05  3.847e+00  
 GV19   -3.167547e+01  3.528536e-08   1.882e-05  3.895e+00  
 GV20   -3.167547e+01  5.788226e-08   5.600e-06  3.769e+00  
 GV21   -3.167547e+01  -8.933793e-09  2.499e-06  3.808e+00  
 GV22   -3.167547e+01  -1.484102e-09  1.118e-06  3.874e+00  
 GV23   -3.167547e+01  9.065753e-10   4.779e-07  3.466e+00  
...
```

It was the same for both my local modified version as well as the latest version of `develop` branch up to Jun 2, 2024.
Can you help look into this matter? Thanks!

Kai

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by WHUweiqingzhou** [comment] 2024-06-03 02:45
@jinzx10, do you think this issue is caused by different two_center integration?

**Comment by jinzx10** [comment] 2024-06-03 06:53
> @jinzx10, do you think this issue is caused by different two_center integration?

I tried turning off the FFT-based two-center integration and tested various values of lcao_ecut, but neither of them is able to reproduce the CentOS result. Here're a few results with the old two-center integration (tested on my desktop WSL2 Ubuntu 22.04):

```
lcao_ecut    ETOT
50           -3.16838360e+01
100          -3.16769820e+01
400          -3.16756880e+01
1600         -3.16754725e+01
```

Given that lcao_ecut is not explicitly given in INPUT, if the old two-center integration is used, the value will be defaulted to ecutwfc=50. Even so, the final etot would be -3.16... instead of -3.13... . Therefore, I think this is not a two-center integration issue.

**Comment by caic99** [comment] 2024-06-06 02:23
> @caic99 do you have any suggestion about how to debug?

@WHUweiqingzhou I would suggest starting from the unit tests of the diagonalization methods.

**Comment by jinzx10** [comment] 2024-11-07 11:01
I can reproduce the results from Debian, but unfortunately I'm unable to build a working CentOS 7.6 environment within a short amount of time. I tried the calculation on the latest fedora wsl and the result is the same as that of Debian. @WHUweiqingzhou 

I think @caic99 's suggestion is a good idea to identify the issue. @kluophysics would you mind compiling abacus on CentOS with all the unit tests by adding "-DBUILD_TESTING=ON", and running those test with "ctest -R" in the build directory?

**Comment by kluophysics** [comment] 2024-11-08 01:25
> I can reproduce the results from Debian, but unfortunately I'm unable to build a working CentOS 7.6 environment within a short amount of time. I tried the calculation on the latest fedora wsl and the result is the same as that of Debian. [@WHUweiqingzhou](https://github.com/WHUweiqingzhou)
> 
> I think [@caic99](https://github.com/caic99) 's suggestion is a good idea to identify the issue. [@kluophysics](https://github.com/kluophysics) would you mind compiling abacus on CentOS with all the unit tests by adding "-DBUILD_TESTING=ON", and running those test with "ctest -R" in the build directory?

Sure, I will try your suggestion but it's going to take sometime.

**Comment by WHUweiqingzhou** [comment] 2024-11-20 06:55
Since we cannot reproduce this issue. We will temporarily close this issue.
Please reopen it if you have any update! @kluophysics

**Closed by WHUweiqingzhou** 2024-11-20 06:55 UTC
Labels: Bugs
