### ISSUE TITLE
Should we support compiling CUDA-based ABACUS with icpx ? 

### ISSUE THREAD

**Issue by maki49** [deepmodeling/abacus-develop#2906] opened 2023-09-05 07:14 UTC
### Details

When I tried to compile ABACUS with `-DCMAKE_CXX_COMPILER=icpx` and `-DUSE_CUDA=1`, such an error occured: 
```
  error: -- unsupported Intel ICX compiler! The nvcc flag
  '-allow-unsupported-compiler' can be used to override this version check;
  however, using an unsupported host compiler may cause compilation failure
  or incorrect run time execution.  Use at your own risk.
```
Is it better to override this check? 

The full error log: [cuda_icpx_err.log](https://github.com/deepmodeling/abacus-develop/files/12519988/cuda_icpx_err.log)

### Have you read FAQ on the online manual http://abacus.deepmodeling.com/en/latest/community/faq.html

- [x] Yes, I have read the FAQ part on online manual.

**Comment by caic99** [comment] 2023-09-06 01:30
Hi @maki49 ,
NVCC has its [host compiler support policy](https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#host-compiler-support-policy). It checks if the version of host compiler is supported. However, overriding this flag is generally OK if this warning is caused by a newer compiler; use at your own risk.

**Comment by QuantumMisaka** [comment] 2023-09-06 08:07
`icpx` compiled ABACUS seems to have problem in `nspin=2` system now ?
https://github.com/deepmodeling/abacus-develop/issues/2889

**Comment by hongriTianqi** [comment] 2023-09-08 04:25
- [ ] Understand the problem or question described by the user.
- [ ] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [ ] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Comment by hongriTianqi** [comment] 2023-09-12 08:44
@denghuilu Do you have more comments on this issue?

**Comment by hongriTianqi** [comment] 2023-09-12 08:48
@maki49 This issue seems out of ABACUS's capability scope. I will close it then.

**Closed as completed by hongriTianqi** 2023-09-12 08:48 UTC
