### ISSUE TITLE
Different stress result obtained for the same example and same running command

### ISSUE THREAD

**Issue by hongriTianqi** [deepmodeling/abacus-develop#1658] opened 2022-12-09 14:01 UTC
### Describe the bug

Different stress result obtained for the same example and same running command

### Expected behavior

The stress result should be consistent with the same example and same running command.

### To Reproduce

Run the example in `~/abacus-develop/tests/integrate/250_NO_KP_CR_VDW3ABC` with the command `OMP_NUM_THREADS=4 mpirun -np 4 abacus`

**Comment by dyzheng** [comment] 2022-12-09 14:34
Can you try to repeat bug by setting "scf_thr 1e-8"?

I guess it may cause by digital difference caused by competition of threads in OMP, which would cause small difference in Hamiltonian matrixes and eigenvectors. 
Stress is more sensitive than energy and forces.
If scf_thr is small enough, tiny digital difference would not affect convergent stresses.

**Comment by hongriTianqi** [comment] 2022-12-09 14:57
> Can you try to repeat bug by setting "scf_thr 1e-8"?
> 
> I guess it may cause by digital difference caused by competition of threads in OMP, which would cause small difference in Hamiltonian matrixes and eigenvectors. Stress is more sensitive than energy and forces. If scf_thr is small enough, tiny digital difference would not affect convergent stresses.

I can try. But the same bug does not happen when I use another command `OMP_NUM_THREADS=1 mpirun -np 8 abacus`

**Comment by dyzheng** [comment] 2022-12-09 15:00
> > Can you try to repeat bug by setting "scf_thr 1e-8"?
> > I guess it may cause by digital difference caused by competition of threads in OMP, which would cause small difference in Hamiltonian matrixes and eigenvectors. Stress is more sensitive than energy and forces. If scf_thr is small enough, tiny digital difference would not affect convergent stresses.
> 
> I can try. But the same bug does not happen when I use another command `OMP_NUM_THREADS=1 mpirun -np 8 abacus`

If you set OMP_NUM_THREADS=1, there is one thread for each process, so no competition of threads occurred. I think it is reasonable.

**Comment by hongriTianqi** [comment] 2022-12-09 15:10
> Can you try to repeat bug by setting "scf_thr 1e-8"?
> 
> I guess it may cause by digital difference caused by competition of threads in OMP, which would cause small difference in Hamiltonian matrixes and eigenvectors. Stress is more sensitive than energy and forces. If scf_thr is small enough, tiny digital difference would not affect convergent stresses.

OK, I have tried. The problem seems persist.
<img width="1098" alt="截屏2022-12-09 下午11 09 03" src="https://user-images.githubusercontent.com/18049272/206732747-91020ebb-1fce-46d3-aa1f-5b2a5177c97b.png">

**Comment by dyzheng** [comment] 2022-12-09 15:15
> > Can you try to repeat bug by setting "scf_thr 1e-8"?
> > I guess it may cause by digital difference caused by competition of threads in OMP, which would cause small difference in Hamiltonian matrixes and eigenvectors. Stress is more sensitive than energy and forces. If scf_thr is small enough, tiny digital difference would not affect convergent stresses.
> 
> OK, I have tried. The problem seems persist. <img alt="截屏2022-12-09 下午11 09 03" width="1098" src="https://user-images.githubusercontent.com/18049272/206732747-91020ebb-1fce-46d3-aa1f-5b2a5177c97b.png">

There is a huge difference occurred, which is abnormal.
I recommend you test without vdw correction, or you can set "test_stress 1" and compare which stress part caused this difference.

**Comment by hongriTianqi** [comment] 2022-12-09 15:16
> > Can you try to repeat bug by setting "scf_thr 1e-8"?
> > I guess it may cause by digital difference caused by competition of threads in OMP, which would cause small difference in Hamiltonian matrixes and eigenvectors. Stress is more sensitive than energy and forces. If scf_thr is small enough, tiny digital difference would not affect convergent stresses.
> 
> OK, I have tried. The problem seems persist. <img alt="截屏2022-12-09 下午11 09 03" width="1098" src="https://user-images.githubusercontent.com/18049272/206732747-91020ebb-1fce-46d3-aa1f-5b2a5177c97b.png">

Add the correct stress should be 40.439895, rather than more than 800...

**Comment by hongriTianqi** [comment] 2022-12-09 15:16
> > > Can you try to repeat bug by setting "scf_thr 1e-8"?
> > > I guess it may cause by digital difference caused by competition of threads in OMP, which would cause small difference in Hamiltonian matrixes and eigenvectors. Stress is more sensitive than energy and forces. If scf_thr is small enough, tiny digital difference would not affect convergent stresses.
> > 
> > 
> > OK, I have tried. The problem seems persist. <img alt="截屏2022-12-09 下午11 09 03" width="1098" src="https://user-images.githubusercontent.com/18049272/206732747-91020ebb-1fce-46d3-aa1f-5b2a5177c97b.png">
> 
> There is a huge difference occurred, which is abnormal. I recommend you test without vdw correction, or you can set "test_stress 1" and compare which stress part caused this difference.

I have tested without vdw3, the same happened.

**Comment by dyzheng** [comment] 2022-12-09 15:18
Recently, there are some PRs about OMP optimization merged into develop branch, which related to force and stress in LCAO base. I will ask if the developer can help for this bug.

**Comment by dyzheng** [comment] 2022-12-09 15:20
@Alcanderian hello, can you help for this issue?

**Comment by hongriTianqi** [comment] 2022-12-09 15:24
> 

OK, the comparison has been made. It seems caused by HAR STRESS.
<img width="1303" alt="截屏2022-12-09 下午11 23 57" src="https://user-images.githubusercontent.com/18049272/206735371-dd8f6bae-b773-4b27-8e4f-d9d7c722b141.png">

**Comment by Alcanderian** [comment] 2022-12-09 16:20
Hello, can you help me to find the boundary conditions for the error?
1. reset the head to `e34af58e0b02e84d454f2be9eea68f6a5e9822e3`
2. run `OMP_NUM_THREADS=2 mpirun -np 4`, `OMP_NUM_THREADS=2 mpirun -np 8`, `OMP_NUM_THREADS=8 mpirun -np 2` , `OMP_NUM_THREADS=8 mpirun -np 1` , `OMP_NUM_THREADS=4 mpirun -np 2`, and `OMP_NUM_THREADS=1 mpirun -np 16`
3. tell which case will cause the error

And also I will try to reproduce on Monday(12/12), Thanks.

**Comment by dyzheng** [comment] 2022-12-09 16:24
> Hello, can you help me to find the boundary conditions for the error?
> 
> 1. reset the head to `e34af58e0b02e84d454f2be9eea68f6a5e9822e3`
> 2. run `OMP_NUM_THREADS=2 mpirun -np 4`, `OMP_NUM_THREADS=2 mpirun -np 8`, `OMP_NUM_THREADS=8 mpirun -np 2` , `OMP_NUM_THREADS=8 mpirun -np 1` , `OMP_NUM_THREADS=4 mpirun -np 2`, and `OMP_NUM_THREADS=1 mpirun -np 16`
> 3. tell which case will cause the error
>    And also I will try to reproduce on Monday(12/12), Thanks.

The test case is https://github.com/deepmodeling/abacus-develop/tree/develop/tests/integrate/250_NO_KP_CR_VDW3ABC
It seems every case which calculated stress with OMP multi threads will induce this bug.

**Comment by Alcanderian** [comment] 2022-12-09 17:04
> > Hello, can you help me to find the boundary conditions for the error?
> > 
> > 1. reset the head to `e34af58e0b02e84d454f2be9eea68f6a5e9822e3`
> > 2. run `OMP_NUM_THREADS=2 mpirun -np 4`, `OMP_NUM_THREADS=2 mpirun -np 8`, `OMP_NUM_THREADS=8 mpirun -np 2` , `OMP_NUM_THREADS=8 mpirun -np 1` , `OMP_NUM_THREADS=4 mpirun -np 2`, and `OMP_NUM_THREADS=1 mpirun -np 16`
> > 3. tell which case will cause the error
> >    And also I will try to reproduce on Monday(12/12), Thanks.
> 
> The test case is https://github.com/deepmodeling/abacus-develop/tree/develop/tests/integrate/250_NO_KP_CR_VDW3ABC It seems every case which calculated stress with OMP multi threads will occur this bug.

Ok, since the CI is passed, I am interesting on how many threads will start to cause this bug. Because if there is no error on 2-thread case but getting error on 4-thread, which is spliting the reduction phase into 16 part, it may cause by the accumulation order of the floating point.
So I also suggest to test the `OMP_NUM_THREADS=1 mpirun -np 16` case. But I am not sure whether the array will be splited into 16 part in this case.

**Comment by hongriTianqi** [comment] 2022-12-09 23:54
> Hello, can you help me to find the boundary conditions for the error?
> 
> 1. reset the head to `e34af58e0b02e84d454f2be9eea68f6a5e9822e3`
> 2. run `OMP_NUM_THREADS=2 mpirun -np 4`, `OMP_NUM_THREADS=2 mpirun -np 8`, `OMP_NUM_THREADS=8 mpirun -np 2` , `OMP_NUM_THREADS=8 mpirun -np 1` , `OMP_NUM_THREADS=4 mpirun -np 2`, and `OMP_NUM_THREADS=1 mpirun -np 16`
> 3. tell which case will cause the error
> 
> And also I will try to reproduce on Monday(12/12), Thanks.

`OMP_NUM_THREADS=2 mpirun -np 4`: error
`OMP_NUM_THREADS=2 mpirun -np 8`: error
`OMP_NUM_THREADS=8 mpirun -np 2`: error
`OMP_NUM_THREADS=8 mpirun -np 1`: error
`OMP_NUM_THREADS=4 mpirun -np 2`: error
`OMP_NUM_THREADS=1 mpirun -np 16`: not applicable on my machine

**Comment by Alcanderian** [comment] 2022-12-12 06:54
@hongriTianqi Hi, you can try whether the bug is fixed by PR #1666

**Comment by hongriTianqi** [comment] 2022-12-12 07:28
> @hongriTianqi Hi, you can try whether the bug is fixed by PR #1666

@Alcanderian All passed. Thanks.

**Closed as completed** 2022-12-12 07:27 UTC
Labels: Bugs
