### ISSUE TITLE
Bandgap values are not the same in running_nscf.log and energy band diagram

### ISSUE THREAD

**Issue by yycx1111** [deepmodeling/abacus-develop#5527] opened 2024-11-19 05:38 UTC
### Describe the bug

I did bandwidth calculation for GaN using PBE dft_functinal with out_bandgap 1. The bandgap is 4.39913 eV. But the band gap of GaN using PBE general function should be around 1.7eV. I used the output file BANDS_1.dat from the non-self-consistent calculations to plot the energy band diagram, and from the energy band diagram I observed that the band gap value is around 1.9eV.

Here is bandgap in running_nscf.log
E_bandgap 4.39913 eV
Here is energy band diagram
[band.zip](https://github.com/user-attachments/files/17810044/band.zip)

### Expected behavior

The bandgap value in running_nscf.log should be the same as the bandgap value shown in the energy band plot

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by ErjieWu** [comment] 2024-11-19 14:16
@yycx1111 
I cannot reproduce your results. Instead, when I try to use INPUT_scf & KPT_scf first for scf calculation and then INPUT_nscf & KPT_nscf for nscf calculation (with files you given and additional setting `out_bandgap=1` for nscf), the result given by running_nscf.log is
E_bandgap 1.8716578909eV
which matches the result in band plot. The version of ABACUS for my test is the latest one (v3.8.3). 
Please check whether you use true input files.

**Comment by yycx1111** [comment] 2024-11-21 15:00
> [@yycx1111](https://github.com/yycx1111) I cannot reproduce your results. Instead, when I try to use INPUT_scf & KPT_scf first for scf calculation and then INPUT_nscf & KPT_nscf for nscf calculation (with files you given and additional setting `out_bandgap=1` for nscf), the result given by running_nscf.log is E_bandgap 1.8716578909eV which matches the result in band plot. The version of ABACUS for my test is the latest one (v3.8.3). Please check whether you use true input files.

I checked the input file and the input file should be right. And calculations using abacus 3.8.3 agree with the results you described. But the bandgap values in the output file running_nscf after calculating with abacus3.8.2 are indeed still wrong. Can you test it with abacus3.8.2?

**Comment by ErjieWu** [comment] 2024-12-23 03:50
@yycx1111 
Thank you for bringing this to our attention. I checked the output of the bandgap label for different versions and found that the error was introduced in v3.7.5 and resolved in v3.8.3. Therefore, the bandgap results and bandstructure results match in v3.7.4 and earlier, as well as v3.8.3 and later. **The bandgap label output is incorrect in the version range of v3.7.5-v3.8.2, and the correct label needs to be referenced from the bandstructure.** Perhaps we should enhance our integration testing to avoid such errors in the future.

**Closed as completed** 2024-12-24 06:20 UTC
Labels: Questions, Unit Tests/Integreate Tests
