### ISSUE TITLE
PW dav scf calculation in GNU is not stable

### ISSUE THREAD

**Issue by pxlxingliang** [deepmodeling/abacus-develop#2351] opened 2023-04-28 03:15 UTC
### Describe the bug

I have a dataset of 10 PW examples running every day, and I find the SCF steps are not stable in GNU compiler.
command is: `OMP_NUM_THREADS =1 mpirun -np 16 abacus`

![image](https://user-images.githubusercontent.com/91927439/235044954-b39d536b-e2a5-4593-b72a-8ba98d5ec366.png)
https://benchmark.mlops.dp.tech/?request=GET%3A%2Fprojects%2Fabacustest%2Fprofiles%2Fabacus-gnu-pw-david

For intel compiler, and command is `OMP_NUM_THREADS =1 mpirun -np 16 abacus`, the SCF steps are stable.
![image](https://user-images.githubusercontent.com/91927439/235044989-9738d200-b2cf-41b2-a188-7e1fd0e5418a.png)
https://benchmark.mlops.dp.tech/?request=GET%3A%2Fprojects%2Fabacustest%2Fprofiles%2Fpw-dav

For intel compiler, and command is `OMP_NUM_THREADS =16 mpirun -np 1 abacus`, the SCF steps are stable.
![image](https://user-images.githubusercontent.com/91927439/235045033-1f42dfd2-d8eb-4030-81bb-f48630c7c458.png)
https://benchmark.mlops.dp.tech/?request=GET%3A%2Fprojects%2Fabacustest%2Fprofiles%2FOMP-intel-dav

By compare the different two runs, we can find that the difference is for 006_27Fe, which is a nspin=2 calculation.
Actually, in issue #2237, we have found that the SCF steps of 006_27Fe is changed after accepting #2070 . 

```
Some key results of 0427, 0428
--------------------------------------------------------------------
example            jobType ScfSteps totalTime(s) converge normal_end 
----               ----        ----         ----     ----       ---- 
000_4GaAs          0427           8        29.66     True       True 
                   0428           8        28.28     True       True 
----               ----        ----         ----     ----       ---- 
001_C2H6O          0427          10        45.24     True       True 
                   0428          10        47.67     True       True 
----               ----        ----         ----     ----       ---- 
002_4MoS2          0427          12        79.82     True       True 
                   0428          12        78.64     True       True 
----               ----        ----         ----     ----       ---- 
003_12Pt111        0427          15       135.40     True       True 
                   0428          15       140.44     True       True 
----               ----        ----         ----     ----       ---- 
004_3BaTiO3        0427          12       236.77     True       True 
                   0428          12       245.14     True       True 
----               ----        ----         ----     ----       ---- 
005_16Na           0427           8       555.55     True       True 
                   0428           8       539.01     True       True 
----               ----        ----         ----     ----       ---- 
006_27Fe           0427          14      1832.40     True       True 
                   0428          16      2221.90     True       True 
----               ----        ----         ----     ----       ---- 
007_32H2O          0427          10        52.70     True       True 
                   0428          10        56.39     True       True 
----               ----        ----         ----     ----       ---- 
008_Li27Ni9O54Mn9C 0427          25      1465.60     True       True 
                   0428          25      1298.40     True       True 
----               ----        ----         ----     ----       ---- 
009_216Si          0427          13      7810.60     True       True 
                   0428          13      7292.90     True       True 
--------------------------------------------------------------------
```

**Comment by haozhihan** [comment] 2023-05-07 04:55
@pxlxingliang Since this issue was introduced after accepting #2070, are the people at Sense Time trying to solve it? or can they provide more information about this issue?

**Comment by pxlxingliang** [comment] 2023-05-07 07:21
> @pxlxingliang Since this issue was introduced after accepting #2070, are the people at Sense Time trying to solve it? or can they provide more information about this issue?

No, I haven't received any replies.

**Comment by hongriTianqi** [comment] 2023-09-09 07:17
- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Closed as completed** 2023-09-20 08:51 UTC
Labels: Bugs
