### ISSUE TITLE
memory usage statistics does not display properly with MPI

### ISSUE THREAD

**Issue by jinzx10** [deepmodeling/abacus-develop#2307] opened 2023-04-23 06:15 UTC
### Describe the bug

For some entries in the memory usage statistics, the total memory consumption across all MPI processes is not equal to the sum of individual consumption within each process. In the attached example, ORB::Table_NR consumes ~10.7 MB within each process, 8 MPI processes are used, but the summary shows 87.0678 or 79.9259 MB, neither of which is correct. Moreover, the output from each process is not the same (which they should).
![image](https://user-images.githubusercontent.com/26805483/233822179-7bb51c14-7fc5-47ac-8ab4-f3949c785662.png)

The problem presumably comes from Memory::print_all in which Parallel_Reduce::reduce_double_all(consume[k]) is called in a descending order of memory consumption. As a consequence, if entries do not have the same order across all process, the reduction would mix the consumptions of different entries. In the above example, Table_NR ranks 8th in some processes and 10th in the others. 87.0678 is the sum of the 8th largest memory entry across all processes, and 79.9259 is the sum of the 10th.

### Expected behavior

The memory usage statistics should properly display the sum of memory consumption of variables across all MPI process.

### To Reproduce

[002_Li88Ge20.zip](https://github.com/deepmodeling/abacus-develop/files/11302910/002_Li88Ge20.zip)

### Environment

Ubuntu 22.04/gnu environment

**Comment by mohanchen** [comment] 2023-04-23 06:41
Seems like a MPI bug

**Comment by jinzx10** [comment] 2023-04-23 07:00
> Seems like a MPI bug

yeah I think the placement of MPI_Allreduce has some problems so that it is not called in an intended way...
Below is the code of print_all. The big for loop between Line 247 & 281 performs the task. I think line 249-263 is finding the index of the i-th largest entry and store the index as k; then on line 265 MPI_Allreduce is called to find the sum of the total memory across all processes. The question is, line 265 actually sums over the k-th largest memory entries across all processes, but those entries might be different variables on different processes.

![image](https://user-images.githubusercontent.com/26805483/233824607-3d3e0935-4dc1-4f1b-936f-5ec50956e4b2.png)

**Comment by wenfei-li** [comment] 2023-04-28 06:12
let me fix it

**Comment by hongriTianqi** [comment] 2023-09-09 07:16
- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by dyzheng** [comment] 2023-10-17 15:40
It is MPI bug which will lead to inexact memory record for some term.
My opinion is it is not an urgent problem because that only close two terms will sorting error in different process. 
The memory results now can be regarded as estimations of terms in program.

**Comment by dyzheng** [comment] 2023-10-17 15:43
The total memory record would not be error with this MPI bug.
However, there are still some objects which allocated memory but not be recorded.

**Comment by WHUweiqingzhou** [comment] 2024-01-31 02:01
This issue has been solved by PR #3109

**Closed as completed by WHUweiqingzhou** 2024-01-31 02:01 UTC
Labels: Bugs
