### ISSUE TITLE
ABACUS crashes when doing relax with gamma_only

### ISSUE THREAD

**Issue by Satinelamp** [deepmodeling/abacus-develop#2643] opened 2023-06-15 08:58 UTC
### Describe the bug

I am trying to set `gamma_only = 1` to accelerate ABACUS, but there is an error showing that 
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  info = 2.
/home/software/abacus-develop/source/module_hsolver/diago_blas.cpp line 343.
degeneracy_need = 206.
degeneracy_saved = 206.
```

Here is the input file and log
[ABACUS-gammaonly-error.zip](https://github.com/deepmodeling/abacus-develop/files/11755274/ABACUS-gammaonly-error.zip)

**Comment by hongriTianqi** [comment] 2023-09-09 07:23
- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by haozhihan** [comment] 2023-10-18 09:04
The basis_type of this case is lcao.

**Comment by pxlxingliang** [comment] 2024-07-16 02:56
Hi @Satinelamp, the error message is about the solve of eigenvalue by scalapack, and the return info is 2, which means:
> If mod(info/2, 2) ≠ 0, then the eigenvectors corresponding to one or more clusters of eigenvalues could not be reorthogonalized because of insufficient workspace. The indices of the clusters are stored in iclustr."
(https://www.ibm.com/docs/en/pessl/5.3.0?topic=easva-pdsygvx-pzhegvx-selected-eigenvalues-optionally-eigenvectors-real-symmetric-complex-hermitian-positive-definite-generalized-eigenproblem)

The process of diagonalization by scalapack is related to the number of parallel cores, and you can try to use more or less parallel cores or use `genelpa` to do the calculation.

I have tested by using 8 cores, and there is no error throwed:
```
 Initial plane wave basis and FFT box
 ---------------------------------------------------------
 -------------------------------------------
 STEP OF RELAXATION : 1
 -------------------------------------------
 START CHARGE      : atomic
 DONE(15.5546    SEC) : INIT SCF
 ITER   ETOT(eV)       EDIFF(eV)      DRHO       TIME(s)    
 GV1    -7.392859e+04  0.000000e+00   1.778e-01  3.796e+01  
 GV2    -7.393608e+04  -7.487902e+00  8.431e-02  2.913e+01  
 GV3    -7.392063e+04  1.544507e+01   6.397e-02  2.905e+01  
 GV4    -7.395205e+04  -3.142076e+01  4.780e-02  2.919e+01  
 GV5    -7.395633e+04  -4.277375e+00  4.062e-02  2.921e+01  
 GV6    -7.395391e+04  2.418247e+00   2.886e-02  2.924e+01  
 GV7    -7.395429e+04  -3.811894e-01  1.489e-02  2.977e+01 
```

**Closed as completed** 2024-07-17 17:03 UTC
Labels: Bugs
