### ISSUE TITLE
Always KILLED BY SIGNAL: 11 (Segmentation fault) in a specific example

### ISSUE THREAD

**Issue by xdzhu** [deepmodeling/abacus-develop#3292] opened 2023-12-03 12:55 UTC
### Describe the bug

Regardless of the pseudopotential used (either Dojo or SG15), I encounter a **segmentation fault (KILLED BY SIGNAL: 11)** that causes an abrupt termination of the process. This issue persists across different cluster systems, whether using PBS or SLURM job scheduling.

The problem occurs with a STRU comprising only 12 atoms.
The issue is reproducible across different computing environments: PBS or SLURM.
This recurrent issue has been a significant hurdle in my computational tasks, and I am keen to understand its root cause and find a resolution. Could you please investigate this matter? Any insights or suggested solutions to overcome this problem would be greatly appreciated.

Thank you for your time and assistance. I am looking forward to your response.
The corresponding input, output, and error information are included in the compressed package. Below are screenshots of the calculations interrupted at different times:

无论我用什么赝势dojo或者sg15，无论是在什么集群上面跑，都会遇到这个报错中途退出 **KILLED BY SIGNAL: 11 (Segmentation fault)** 。我在不同的计算系统上面跑过，无论是PBS还是SLURM，均出现此问题。

这个结构总共只有12个原子，相应的输入输出和报错信息已包含在压缩包内，非常感谢复现此问题并给出解决方案，谢谢！

[signal11-issue.zip](https://github.com/deepmodeling/abacus-develop/files/13538947/signal11-issue.zip)

下面是在不同时候中断的计算截图：

![image](https://github.com/deepmodeling/abacus-develop/assets/55775434/e5fb3c6f-42cf-42a6-baac-1325ed399e47)
![image](https://github.com/deepmodeling/abacus-develop/assets/55775434/a9cce821-816d-4c27-974e-e0a537b52930)
![image](https://github.com/deepmodeling/abacus-develop/assets/55775434/c165adb0-e0b9-4c72-b968-d26bea5921bb)
![image](https://github.com/deepmodeling/abacus-develop/assets/55775434/cbd2f1bc-0aa8-48d0-81a9-3b6149237be9)

### Task list for Issue attackers (only for developers)

- [ ] Verify the issue is not a duplicate.
- [ ] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by dyzheng** [comment] 2023-12-04 03:09
Can you try "ks_solver scalapack_gvx"?

**Comment by xdzhu** [comment] 2023-12-05 10:32
@dyzheng Thank you very much! I've tried "ks_solver scalapack_gvx". The whole cell-relax calculation can work well and finally reach the force threshold.

So I have another question now: since changing the ks_solver can solve this issue, it suggests that the **Segmentation fault is caused by genelpa**. However, there are only 12 atoms in my system, which seems unlikely to cause a memory problem. What could be the reason for this?

**Comment by caic99** [comment] 2023-12-07 08:59
> So I have another question now: since changing the ks_solver can solve this issue, it suggests that the **Segmentation fault is caused by genelpa**. However, there are only 12 atoms in my system, which seems unlikely to cause a memory problem. What could be the reason for this?

Hi @xdzhu Please note that segmentation fault is usually caused by erroneous memory access, while out of memory error usually produces signal 9. They are different errors.

**Comment by xdzhu** [comment] 2023-12-07 09:03
> > So I have another question now: since changing the ks_solver can solve this issue, it suggests that the **Segmentation fault is caused by genelpa**. However, there are only 12 atoms in my system, which seems unlikely to cause a memory problem. What could be the reason for this?
> 
> Hi @xdzhu Please note that segmentation fault is usually caused by erroneous memory access, while out of memory error usually produces signal 9. They are different errors.

Thanks for your reply. And why it is always KILLED BY SIGNAL: 11 (Segmentation fault) when using "ks_solver genelpa" in this specific system?

**Comment by caic99** [comment] 2023-12-07 09:46
> Thanks for your reply. And why it is always KILLED BY SIGNAL: 11 (Segmentation fault) when using "ks_solver genelpa" in this specific system?

This error might be related to ELPA and the libraries it uses. Maybe certain system setup triggers the hidden bug. Similar issue: #2816

**Comment by xdzhu** [comment] 2024-01-15 10:29
This problem of elpa memory leak has been solved by @caic99 in [**Release v3.5.1**](https://github.com/deepmodeling/abacus-develop/releases/tag/v3.5.1) .

I have tested this specific example with the version of 3.5.1 rather than 3.4.3, now one can set the `ks_solver` to "elpa" **without encountering the memory leak problem anymore**. BTW, it is worth mentioning that the calculation speed has also increased.

Test result as below:
![image](https://github.com/deepmodeling/abacus-develop/assets/55775434/4a75ac79-45c8-4a68-9fc5-76eac91493ca)

**Comment by caic99** [comment] 2024-01-16 03:51
> This problem of elpa memory leak has been solved by @caic99 in [**Release v3.5.1**](https://github.com/deepmodeling/abacus-develop/releases/tag/v3.5.1) .
> 
> I have tested this specific example with the version of 3.5.1 rather than 3.4.3, now one can set the `ks_solver` to "elpa" **without encountering the memory leak problem anymore**. BTW, it is worth mentioning that the calculation speed has also increased.

@xdzhu Glad to hear that! Closing this issue. However, please note that the problem you encountered is not memory leak, which often results in OOM error.

> Hi @xdzhu Please note that segmentation fault is usually caused by erroneous memory access, while out of memory error usually produces signal 9. They are different errors.

**Closed as completed by caic99** 2024-01-16 03:51 UTC
Labels: Bugs
