### ISSUE TITLE
Different electrostatic potential results from QE

### ISSUE THREAD

**Issue by sunml99** [deepmodeling/abacus-develop#2838] opened 2023-08-16 08:56 UTC
### Details

We calculated the average electrostatic potential(ESP) for a Pt_slab system using QE and ABACUS, but the outputs seem not consistent. There is a shift (~0.05 Ry) between the two ESPs as shown in the attached figure. The outputs of ABACUS and QE are the attached ElecStaticPot_AVE and avg.dat files, respectively. In the QE output, the planar average is the 2nd column as a function of the 1st one.

I would like to know if there is a problem with my input parameters, or if this function is different in the two software. Thanks a lot.

![1390cb9341429c34146274cb1eb0a1d](https://github.com/deepmodeling/abacus-develop/assets/91242172/33052958-0764-4cb2-9130-b9a6f7a5ecb3)
[ESP_results.zip](https://github.com/deepmodeling/abacus-develop/files/12357447/ESP_results.zip)

**Comment by dyzheng** [comment] 2023-08-23 12:38
It looks there is a deviation between ABACUS and QE, I think your parameters is equivalence between two code.

There are three suggestions to diagnose the problem:
1. test ABACUS with 1 core only.
2. test ABACUS and QE with scf_nmax=1 and mixing_beta=0, which means output ESP with atomic charge.
3. test ABACUS with GNU compiler.(image:  registry.dp.tech/deepmodeling/abacus-gnu:latest).

If 1 cause same results between ABACUS and QE, it means MPI parallel for ABACUS lead to digital error.
If 2 cause same results between ABACUS and QE, it means charge-mixing lead to digital error.
if 3 cause same results between ABACUS and QE, it means Intel compiler lead to digital error.

**Comment by hongriTianqi** [comment] 2023-09-08 04:45
- [x] Understand the problem or question described by the user.
- [x] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [ ] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Comment by hongriTianqi** [comment] 2023-09-09 09:49
@sunml99 Have you tried to further look into the problem according to @dyzheng 's suggestions?

**Comment by sunml99** [comment] 2023-09-10 09:17
> 
I haven't tried these suggestions yet.

I later found that although the system's total energy is the same under the current parameters, some energies such as the Hartree and XC terms are still different from QE (~0.04 Ry). Under the suggestion of Mr. Chen, I tried to adjust scf_thr from 1E-6 to 1E-9, which solved the corresponding problem of each part of the energy but I found that it was not helpful to the electrostatic potential. Now we are still looking for the reason.

**Comment by YuLiu98** [comment] 2023-09-19 13:48
I found a bug in calculating electrostatic potential.

After fixing it, the esp is the same as that of QE.

I will submit a PR to fix it.

Here is the result: [esp.tar.gz](https://github.com/deepmodeling/abacus-develop/files/12660965/esp.tar.gz)

**Closed as completed** 2023-09-20 01:21 UTC
