### ISSUE TITLE
When performing SCF calculations using SCAN+vdW or PBE+vdW, the pressure is shown as NaN

### ISSUE THREAD

**Issue by Chentao168** [deepmodeling/abacus-develop#2829] opened 2023-08-14 11:51 UTC
### Describe the bug

When performing SCF calculations using SCAN+vdW (D3(0)) or PBE+vdW (D3(0)), the pressure is shown as nan. Without adding vdW corrections, the calculation results are correct.

### To Reproduce
[20230814-nan.zip](https://github.com/deepmodeling/abacus-develop/files/12334766/20230814-nan.zip)

**Comment by hongriTianqi** [comment] 2023-09-08 04:48
- [x] Verify the issue is not a duplicate.
- [x] Describe the bug.
- [ ] Steps to reproduce.
- [ ] Expected behavior.
- [ ] Error message.
- [ ] Environment details.
- [ ] Additional context.
- [ ] Assign a priority level (low, medium, high, urgent).
- [ ] Assign the issue to a team member.
- [ ] Label the issue with relevant tags.
- [ ] Identify possible related issues.
- [ ] Create a unit test or automated test to reproduce the bug (if applicable).
- [ ] Fix the bug.
- [ ] Test the fix.
- [ ] Update documentation (if necessary).
- [ ] Close the issue and inform the reporter (if applicable).

**Comment by 1041176461** [comment] 2023-09-18 02:10
I think you should check if your structure is correct, （maybe you used the wrong unit). In your PBE results, stress has reached more than 300,000 kBAR:
![image](https://github.com/deepmodeling/abacus-develop/assets/40336950/b0e25698-0f5c-4a28-a085-ae11badfb41a)
And the program has warned you that the atoms in your structure are too close:
![image](https://github.com/deepmodeling/abacus-develop/assets/40336950/75c5b6f0-66c1-4cd0-8fa7-94d5151071f2)
I also test Si with your INPUT, the output is normal:
![image](https://github.com/deepmodeling/abacus-develop/assets/40336950/a143f1a4-d6c7-4f00-b6f1-451ab88e1ad9)

**Comment by hongriTianqi** [comment] 2023-11-21 06:55
@Chentao168 Do you have more questions on this issue? If not, we may close this issue. Thanks

**Closed as completed** 2023-11-21 07:02 UTC
Labels: Bugs

**Comment by hongriTianqi** [comment] 2023-11-28 01:55
@Chentao168 Can you reply if this issue has been solved?

**Comment by Chentao168** [comment] 2023-11-29 02:31
The issue has been solved.
