### ISSUE TITLE
Remove warning status in CI tests

### ISSUE THREAD

**Issue by YuLiu98** [deepmodeling/abacus-develop#2552] opened 2023-05-28 03:03 UTC
### Describe Current Status and Possible Solution

Now the CI tests have three statuses: `OK`, `WARNING`, and `ERROR`.

However, we **cannot** realize the occurrence of the `WARNING` status, unless we click the button in the PR page and check the integrated tests in detail, which causes the accumulation of tests with the `WARNING` status. 

So. I suggest removing the `WARNING` status in order to make sure no warnings are introduced by PRs.

**Comment by hongriTianqi** [comment] 2023-09-09 07:41
- [ ] Understand the problem or question described by the user.
- [ ] Check if the issue is a known problem or has been addressed in the documentation.
- [ ] Test the issue or problem on a similar system or environment, if possible.
- [ ] Identify the root cause or provide clarification on the user's question.
- [ ] Provide a step-by-step guide, including any necessary resources, to resolve the issue or answer the question.
- [ ] If the issue is related to documentation, update the documentation to prevent future confusion (optional).
- [ ] If the issue is related to code, consider implementing a fix or improvement (optional).
- [ ] Review and incorporate any relevant feedback from users or developers.
- [ ] Ensure the user's issue is resolved or their question is answered and close the ticket.

**Closed as completed** 2024-06-06 08:50 UTC
Labels: Compile & CICD & Docs & Dependencies
